$axure.loadCurrentPage({
  "url":"业务终端.html",
  "generationDate":new Date(1482495099502.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"69edff6d28634270a7263bf63ccfcf47",
    "type":"Axure:Page",
    "name":"业务终端",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc3e138dea0443f7a7bac2a9bba32bc1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":7,
              "y":3},
            "size":{
              "width":185,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e852856eaf774016834af4a20b3eae79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":7,
                  "y":3},
                "size":{
                  "width":185,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"57d98029a1d34807a09854615ea3aeb1",
          "label":"跨境结算简介",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":390},
            "size":{
              "width":750,
              "height":680}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f5661866869b4e4d8321922d6b7b7605",
              "label":"返回信息",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2769d05669d74436b2b785957331dc5e",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "selected":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}},
                      "selected":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}}},
                    "size":{
                      "width":250,
                      "height":40},
                    "outerShadow":{
                      "on":false,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bd36aa03a443481ab479e4dd6ecafe79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}},
                          "selected":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}}},
                        "size":{
                          "width":250,
                          "height":40},
                        "outerShadow":{
                          "on":false,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 跨境结算简介 to 返回信息",
                              "panelsToStates":[{
                                  "panelPath":["57d98029a1d34807a09854615ea3aeb1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/业务终端/u3.png",
                    "selected~":"images/业务终端/u3.png",
                    "mouseOver~":"images/业务终端/u3.png"}},
{
                  "id":"9dd0729743c449638cd968c9543fc45c",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}},
                      "selected":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}}},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":250,
                      "height":40},
                    "outerShadow":{
                      "on":false,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9315a1288b6140ee982641fe63a4c19b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}},
                          "selected":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}}},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":250,
                          "height":40},
                        "outerShadow":{
                          "on":false,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 跨境结算简介 to 返回源码",
                              "panelsToStates":[{
                                  "panelPath":["57d98029a1d34807a09854615ea3aeb1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/业务终端/u3.png",
                    "selected~":"images/业务终端/u3.png",
                    "mouseOver~":"images/业务终端/u3.png"}},
{
                  "id":"ba63ffc92d9a4fbf8905c2b428a143e5",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":709,
                      "height":67}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"087c76c6e70249a7b50c48c2c33333d7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":709,
                          "height":67}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6fac608bd0774c4ca8b23e3f37162c9e",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"left",
                    "location":{
                      "x":19,
                      "y":389},
                    "size":{
                      "width":708,
                      "height":91},
                    "cornerRadiusTopLeft":"13"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"392a4f94474140f68fb50e668b3488ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"left",
                        "location":{
                          "x":19,
                          "y":389},
                        "size":{
                          "width":708,
                          "height":91},
                        "cornerRadiusTopLeft":"13"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u9.png"}},
{
                  "id":"890dbc8ee31c4fba8c05d2cc9f46397f",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":307},
                    "size":{
                      "width":709,
                      "height":62}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f69dbe9810754b309995f32ba7c86d32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":307},
                        "size":{
                          "width":709,
                          "height":62}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"258996ef026d41a38f20826e5f83c2c4",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":19,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"477bf4bf6c0a4f2c95628b6dcc749525",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":19,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"42b2763d5b414503938d597512a022b4",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"980617d161af4be093ac45b3bafbfecd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u15.png"}},
{
                  "id":"a6fca950928f408a823dfe4278f90d13",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":109,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e06b2d3ad7034e2b851d4c1c3a4e46fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":109,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"ee181fb58197469cb74d3c89c4c7df1a",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":111,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f37adff7fc82461792f22f886d946c0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":111,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u19.png"}},
{
                  "id":"1ebbaa01f6484bfc86161b4f5596aaef",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":199,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47f1ea20420448ad8970c66ca27e35a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":199,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"030d6ed5a3c34f15806af997dffc417f",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":201,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dcb16533f4574934bb7c837700c63e3d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":201,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u23.png"}},
{
                  "id":"cb89c500e44e4ef3bf265dd6390f2b18",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":469,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93c74177e15743a1bebdb2e41cef5c93",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":469,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"3d9ef94e634549a288d08f69f1e514e4",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":471,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"60ac39a748cb44a9af373460cb18439d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":471,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u27.png"}},
{
                  "id":"26c7c877fc8d4a9bbff2c64c6533b0ff",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":289,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"98d90c38ffc34984971f6e6c0f9be593",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":289,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"d6d5181d93e443dea09d1b40671c8c60",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":291,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a45eca8a13f340d2b24250e8f532c196",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":291,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u31.png"}},
{
                  "id":"03b9358827ed4898b59e5045a2602f11",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":379,
                      "y":137},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29985f9d874342409f9758224b2fe452",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":379,
                          "y":137},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"4806e8943a8048a9be5ca4412efcb312",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":381,
                      "y":139},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1668b2d560d449090dca3b5956339e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":381,
                          "y":139},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u35.png"}},
{
                  "id":"d6d1a46702f1476d9b100c2c2b9e8097",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":559,
                      "y":139},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a3825ce665f346c4af339172f490a236",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":559,
                          "y":139},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"ed5f6ca93d684fcc8d603566c4e63908",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":561,
                      "y":141},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4885f6fea7e459eb038e758f4f9733d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":561,
                          "y":141},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u39.png"}},
{
                  "id":"c1c59d03a7174b08be8bb88e16131565",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":649,
                      "y":139},
                    "size":{
                      "width":80,
                      "height":120},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFDDDDDD},
                    "cornerRadiusTopLeft":"4"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bfadec419fe04519aed5d5fb91feb777",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":649,
                          "y":139},
                        "size":{
                          "width":80,
                          "height":120},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFDDDDDD},
                        "cornerRadiusTopLeft":"4"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u13.png"}},
{
                  "id":"ad0e113dba0e42429897ff321e199f51",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":651,
                      "y":141},
                    "size":{
                      "width":76,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d2957f01653a4cb6b4576856612fcc93",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":651,
                          "y":141},
                        "size":{
                          "width":76,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务终端/u43.png"}}]},
{
              "id":"64ddbae4f2df49cdaa9d7d141859a921",
              "label":"返回源码",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1d51259ffafe4a4eb6ee7ac527fe56c3",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}},
                      "selected":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}}},
                    "size":{
                      "width":250,
                      "height":40},
                    "outerShadow":{
                      "on":false,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0b5dd3f36ac54805a348d40bc29fc81a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}},
                          "selected":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}}},
                        "size":{
                          "width":250,
                          "height":40},
                        "outerShadow":{
                          "on":false,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 跨境结算简介 to 返回信息",
                              "panelsToStates":[{
                                  "panelPath":["57d98029a1d34807a09854615ea3aeb1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/业务终端/u3.png",
                    "selected~":"images/业务终端/u3.png",
                    "mouseOver~":"images/业务终端/u3.png"}},
{
                  "id":"1a5ee6940d734635b0b8e05e72cda0c1",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "selected":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "stateStyles":{
                      "mouseOver":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}},
                      "selected":{
                        "underline":true,
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1}}},
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":250,
                      "height":40},
                    "outerShadow":{
                      "on":false,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6fffffc1c4a04d2487140933a7aa6388",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "stateStyles":{
                          "mouseOver":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}},
                          "selected":{
                            "underline":true,
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFFFF0000,
                              "opacity":1}}},
                        "location":{
                          "x":250,
                          "y":0},
                        "size":{
                          "width":250,
                          "height":40},
                        "outerShadow":{
                          "on":false,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 跨境结算简介 to 返回源码",
                              "panelsToStates":[{
                                  "panelPath":["57d98029a1d34807a09854615ea3aeb1"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/业务终端/u3.png",
                    "selected~":"images/业务终端/u3.png",
                    "mouseOver~":"images/业务终端/u3.png"}},
{
                  "id":"c81b7e3d52ec48c88e63e8025eaacac0",
                  "label":"",
                  "parentDynamicPanel":"57d98029a1d34807a09854615ea3aeb1",
                  "type":"inlineFrame",
                  "styleType":"inlineFrame",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":40},
                    "size":{
                      "width":750,
                      "height":620}},
                  "adaptiveStyles":{
}}]}]},
{
          "id":"ed4687e42fef4a339a2347f208de452a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":65,
              "y":112},
            "size":{
              "width":615,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"225e013ec24b46d7a2333092f8da4c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":65,
                  "y":112},
                "size":{
                  "width":615,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务终端/u50.png"}},
{
          "id":"f0c1c598c0b9456895943e9de284afa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":484,
              "y":122},
            "size":{
              "width":169,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc38d001d9f44643a5301d8e00db9aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":484,
                  "y":122},
                "size":{
                  "width":169,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb155af224ab440693133d00cfa46053",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":620,
              "y":182},
            "size":{
              "width":160,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1df377789cf436599876b37ef3b95ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":620,
                  "y":182},
                "size":{
                  "width":160,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc3e138dea0443f7a7bac2a9bba32bc1":{
      "scriptId":"u0"},
    "e852856eaf774016834af4a20b3eae79":{
      "scriptId":"u1"},
    "57d98029a1d34807a09854615ea3aeb1":{
      "scriptId":"u2"},
    "2769d05669d74436b2b785957331dc5e":{
      "scriptId":"u3"},
    "bd36aa03a443481ab479e4dd6ecafe79":{
      "scriptId":"u4"},
    "9dd0729743c449638cd968c9543fc45c":{
      "scriptId":"u5"},
    "9315a1288b6140ee982641fe63a4c19b":{
      "scriptId":"u6"},
    "ba63ffc92d9a4fbf8905c2b428a143e5":{
      "scriptId":"u7"},
    "087c76c6e70249a7b50c48c2c33333d7":{
      "scriptId":"u8"},
    "6fac608bd0774c4ca8b23e3f37162c9e":{
      "scriptId":"u9"},
    "392a4f94474140f68fb50e668b3488ad":{
      "scriptId":"u10"},
    "890dbc8ee31c4fba8c05d2cc9f46397f":{
      "scriptId":"u11"},
    "f69dbe9810754b309995f32ba7c86d32":{
      "scriptId":"u12"},
    "258996ef026d41a38f20826e5f83c2c4":{
      "scriptId":"u13"},
    "477bf4bf6c0a4f2c95628b6dcc749525":{
      "scriptId":"u14"},
    "42b2763d5b414503938d597512a022b4":{
      "scriptId":"u15"},
    "980617d161af4be093ac45b3bafbfecd":{
      "scriptId":"u16"},
    "a6fca950928f408a823dfe4278f90d13":{
      "scriptId":"u17"},
    "e06b2d3ad7034e2b851d4c1c3a4e46fd":{
      "scriptId":"u18"},
    "ee181fb58197469cb74d3c89c4c7df1a":{
      "scriptId":"u19"},
    "f37adff7fc82461792f22f886d946c0e":{
      "scriptId":"u20"},
    "1ebbaa01f6484bfc86161b4f5596aaef":{
      "scriptId":"u21"},
    "47f1ea20420448ad8970c66ca27e35a4":{
      "scriptId":"u22"},
    "030d6ed5a3c34f15806af997dffc417f":{
      "scriptId":"u23"},
    "dcb16533f4574934bb7c837700c63e3d":{
      "scriptId":"u24"},
    "cb89c500e44e4ef3bf265dd6390f2b18":{
      "scriptId":"u25"},
    "93c74177e15743a1bebdb2e41cef5c93":{
      "scriptId":"u26"},
    "3d9ef94e634549a288d08f69f1e514e4":{
      "scriptId":"u27"},
    "60ac39a748cb44a9af373460cb18439d":{
      "scriptId":"u28"},
    "26c7c877fc8d4a9bbff2c64c6533b0ff":{
      "scriptId":"u29"},
    "98d90c38ffc34984971f6e6c0f9be593":{
      "scriptId":"u30"},
    "d6d5181d93e443dea09d1b40671c8c60":{
      "scriptId":"u31"},
    "a45eca8a13f340d2b24250e8f532c196":{
      "scriptId":"u32"},
    "03b9358827ed4898b59e5045a2602f11":{
      "scriptId":"u33"},
    "29985f9d874342409f9758224b2fe452":{
      "scriptId":"u34"},
    "4806e8943a8048a9be5ca4412efcb312":{
      "scriptId":"u35"},
    "f1668b2d560d449090dca3b5956339e6":{
      "scriptId":"u36"},
    "d6d1a46702f1476d9b100c2c2b9e8097":{
      "scriptId":"u37"},
    "a3825ce665f346c4af339172f490a236":{
      "scriptId":"u38"},
    "ed5f6ca93d684fcc8d603566c4e63908":{
      "scriptId":"u39"},
    "f4885f6fea7e459eb038e758f4f9733d":{
      "scriptId":"u40"},
    "c1c59d03a7174b08be8bb88e16131565":{
      "scriptId":"u41"},
    "bfadec419fe04519aed5d5fb91feb777":{
      "scriptId":"u42"},
    "ad0e113dba0e42429897ff321e199f51":{
      "scriptId":"u43"},
    "d2957f01653a4cb6b4576856612fcc93":{
      "scriptId":"u44"},
    "1d51259ffafe4a4eb6ee7ac527fe56c3":{
      "scriptId":"u45"},
    "0b5dd3f36ac54805a348d40bc29fc81a":{
      "scriptId":"u46"},
    "1a5ee6940d734635b0b8e05e72cda0c1":{
      "scriptId":"u47"},
    "6fffffc1c4a04d2487140933a7aa6388":{
      "scriptId":"u48"},
    "c81b7e3d52ec48c88e63e8025eaacac0":{
      "scriptId":"u49"},
    "ed4687e42fef4a339a2347f208de452a":{
      "scriptId":"u50"},
    "225e013ec24b46d7a2333092f8da4c09":{
      "scriptId":"u51"},
    "f0c1c598c0b9456895943e9de284afa7":{
      "scriptId":"u52"},
    "dc38d001d9f44643a5301d8e00db9aa7":{
      "scriptId":"u53"},
    "bb155af224ab440693133d00cfa46053":{
      "scriptId":"u54"},
    "a1df377789cf436599876b37ef3b95ac":{
      "scriptId":"u55"}}});