$axure.loadCurrentPage({
  "url":"applications.html",
  "generationDate":new Date(1482495100256.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3e01d95d291243f397411b34cf09e1dd",
    "type":"Axure:Page",
    "name":"applications",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"118a94bb4603472d84d3db42fd0484d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":20},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85c85e921ba64232b1591315ad3d4de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":460,
                  "y":20},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6490e546d32a4b00915d7ffe68a3289c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":0,
              "y":81},
            "size":{
              "width":721,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ae04e5e2ba14d49bc15b7b5480a22a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":0,
                  "y":81},
                "size":{
                  "width":721,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"29f443b4e95e421aa306054099b317a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":30,
              "y":120},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92fc79d31a84d938cdeb00fb2df9f9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":30,
                  "y":120},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/applications/u4_selected.png",
            "mouseOver~":"images/applications/u4_selected.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"b9fbece0f72b424a953633310b5e9d28",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54a7069edbee465da33254a286468bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/applications/u4_selected.png",
            "mouseOver~":"images/applications/u4_selected.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"0d7c3914231244b99c3a53f3d0dcfb2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":470,
              "y":120},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"081911f894ca469390283393aa1bdf8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":470,
                  "y":120},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/applications/u4_selected.png",
            "mouseOver~":"images/applications/u4_selected.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"0328846abb3c464d8254fccff3486c22",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":690,
              "y":120},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5161ed3582eb419a922989d7da50ff84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":690,
                  "y":120},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/applications/u4_selected.png",
            "mouseOver~":"images/applications/u4_selected.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"3381cd31877c4bfb846a6ceaa5742253",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0066FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF333333,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":909,
              "y":120},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad7153cd2b0b40e98340bbe6163aa7d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0066FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":909,
                  "y":120},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/applications/u4_selected.png",
            "mouseOver~":"images/applications/u4_selected.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"df12aca2d8a84435af3a78441f9b50b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":0,
              "y":170},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a857bcbdcdb746d395d8e66090cc1025",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":0,
                  "y":170},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93f26e513db348efbb08f81b0919ffe1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":220,
              "y":170},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c272df8c9732498b931f61791111f9a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":220,
                  "y":170},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c37e56fae953446b965ad8167eea6b3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":440,
              "y":170},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"871829dc6cae494997cba90e58bddc8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":440,
                  "y":170},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b5730ea36243989f299fb1b920abe6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":660,
              "y":170},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38250f2eb3ad464786f9466581fabcf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":660,
                  "y":170},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"09198512d1cf4108ac49c9766ed2fcd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":879,
              "y":170},
            "size":{
              "width":161,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff00701f4944795b102abfa2c65f520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":879,
                  "y":170},
                "size":{
                  "width":161,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"292095f4b7eb4af9a65d9277ec78b7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":990,
              "y":81},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"250f9b62dd8d429f96d87fa01b9535e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":990,
                  "y":81},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "118a94bb4603472d84d3db42fd0484d3":{
      "scriptId":"u0"},
    "85c85e921ba64232b1591315ad3d4de4":{
      "scriptId":"u1"},
    "6490e546d32a4b00915d7ffe68a3289c":{
      "scriptId":"u2"},
    "8ae04e5e2ba14d49bc15b7b5480a22a6":{
      "scriptId":"u3"},
    "29f443b4e95e421aa306054099b317a8":{
      "scriptId":"u4"},
    "f92fc79d31a84d938cdeb00fb2df9f9d":{
      "scriptId":"u5"},
    "b9fbece0f72b424a953633310b5e9d28":{
      "scriptId":"u6"},
    "54a7069edbee465da33254a286468bea":{
      "scriptId":"u7"},
    "0d7c3914231244b99c3a53f3d0dcfb2d":{
      "scriptId":"u8"},
    "081911f894ca469390283393aa1bdf8b":{
      "scriptId":"u9"},
    "0328846abb3c464d8254fccff3486c22":{
      "scriptId":"u10"},
    "5161ed3582eb419a922989d7da50ff84":{
      "scriptId":"u11"},
    "3381cd31877c4bfb846a6ceaa5742253":{
      "scriptId":"u12"},
    "ad7153cd2b0b40e98340bbe6163aa7d6":{
      "scriptId":"u13"},
    "df12aca2d8a84435af3a78441f9b50b8":{
      "scriptId":"u14"},
    "a857bcbdcdb746d395d8e66090cc1025":{
      "scriptId":"u15"},
    "93f26e513db348efbb08f81b0919ffe1":{
      "scriptId":"u16"},
    "c272df8c9732498b931f61791111f9a1":{
      "scriptId":"u17"},
    "c37e56fae953446b965ad8167eea6b3d":{
      "scriptId":"u18"},
    "871829dc6cae494997cba90e58bddc8a":{
      "scriptId":"u19"},
    "27b5730ea36243989f299fb1b920abe6":{
      "scriptId":"u20"},
    "38250f2eb3ad464786f9466581fabcf2":{
      "scriptId":"u21"},
    "09198512d1cf4108ac49c9766ed2fcd4":{
      "scriptId":"u22"},
    "eff00701f4944795b102abfa2c65f520":{
      "scriptId":"u23"},
    "292095f4b7eb4af9a65d9277ec78b7dd":{
      "scriptId":"u24"},
    "250f9b62dd8d429f96d87fa01b9535e4":{
      "scriptId":"u25"}}});