$axure.loadCurrentPage({
  "url":"solutions.html",
  "generationDate":new Date(1482495099951.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"923d2252a0b74e429ec1043c70171bbd",
    "type":"Axure:Page",
    "name":"Solutions",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2678c4a61b1e4756b85dbe96a383a8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":496,
              "y":10},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2164c08865404cbc00df5bf7c285cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":496,
                  "y":10},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00bbb9095cc843b0b1b88eb67da80f5c",
          "label":"合规认证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":70},
            "size":{
              "width":545,
              "height":260}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0c141de278314d60801afd63b06c6211",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"92e90a39d3f14186b3f278f94cd75f4f",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":545,
                      "height":230},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fbcae97b5a804716b2f49643a3afeb93",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":545,
                          "height":230},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u3.png"}},
{
                  "id":"932098d429774e839821543a20d6e5a7",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":120,
                      "y":50},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11737b436d3046d3ab1464ccfeb3ab1f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":120,
                          "y":50},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"571005b68afd41f88e83b96d6426b045",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":50},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa9768880dc54530bc9a605cf070c611",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":50},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"ab1dbb4fc2424cee8abda45b766bdab6",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":50},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd26bd27579a41a48aee979d26f00592",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":50},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"7e32d1edda144bfc8a3d46ee9e319f6a",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":17,
                      "y":82},
                    "size":{
                      "width":93,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e847cf2c8cf496aa5999bc03b703105",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":17,
                          "y":82},
                        "size":{
                          "width":93,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0744357ebcdc45928cfdbba80ae4dedf",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":17,
                      "y":111},
                    "size":{
                      "width":93,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4e1be3a7e23649c898ae5c5f61336e37",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":17,
                          "y":111},
                        "size":{
                          "width":93,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"26de0cef33704e5fbd73a29ea09d40dd",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":17,
                      "y":140},
                    "size":{
                      "width":93,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a6cf66dcf7a43f58b5d22aacc1fd47a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":17,
                          "y":140},
                        "size":{
                          "width":93,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a0983b2c96544318be377d29bd08af99",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":17,
                      "y":169},
                    "size":{
                      "width":93,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e82459d9a7f48cfa194d42db202c6e5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":17,
                          "y":169},
                        "size":{
                          "width":93,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"84df29155f404e689241ce0c418eecdf",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cff95e496685487b8c8869f998ef63e6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"5f5f4170a0ea4086abc5ced9db9a54f9",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":486,
                      "y":14},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57accaa119de468887a4444f35d6ec89",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":486,
                          "y":14},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b5c7c9af5b914497b391bfdf6724662b",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":470,
                      "y":234},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f38d6be0e97540e69bf5b54e906ce176",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":470,
                          "y":234},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"86aa7da0da224d1db4bb3e33a8c9054d",
                  "label":"",
                  "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":397,
                      "y":234},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"aab96f05761748598b057a526f76d568",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"00bbb9095cc843b0b1b88eb67da80f5c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":397,
                          "y":234},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"7d68e11cddb24471a206a7d9f27e6aaf",
          "label":"合规认证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":70},
            "size":{
              "width":545,
              "height":260}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ef1b0f5d87964f66951354a6571cf6ef",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9739f36f734947f9bb94d0d20e0cb878",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":545,
                      "height":230},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7cb346b5e5a64c21b98fcbed9fba0a21",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":545,
                          "height":230},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u3.png"}},
{
                  "id":"d6efaccc0bc94fa09919103a3e2bcf79",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05a0229558de4c829c53ae97e0178144",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"47cdaa26dbb440f586e4bc86f7d82bef",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df4e62b138fc4adaa432b371ee935130",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":472,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d2a99193a98347c39c68c67c0cd7c017",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":14,
                      "y":34},
                    "size":{
                      "width":517,
                      "height":190}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1c0c335f1b24407eaade4e52ae343ab7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":14,
                          "y":34},
                        "size":{
                          "width":517,
                          "height":190}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"26785c871a174a4b98821bafe65b4a15",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":470,
                      "y":234},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d67ddb194dd4dfda9b1500e8d40c30e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":470,
                          "y":234},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"35a0094a1b1e458eb012e6c576163ff6",
                  "label":"",
                  "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":397,
                      "y":234},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"06dae1aa71c14e1d9808e2b43e63f6e2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d68e11cddb24471a206a7d9f27e6aaf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":397,
                          "y":234},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"636acf13ec714cf3acc9280be6a368ac",
          "label":"合规认证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":680},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0cbb9c44f74f435bbec89208bd03a605",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"937aec61d2844f6d9eb199c98843741d",
                  "label":"",
                  "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":360,
                      "height":129},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9767cee9e505495487164ec2b134e2fa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":360,
                          "height":129},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u41.png"}},
{
                  "id":"a9da72997e69420a9b86de2002184b9f",
                  "label":"",
                  "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"90caf53122d14bd5957fc8c0495f718a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"9653b81196944d9bb859feac1bc94353",
                  "label":"",
                  "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"75da27d416f84387862facfe444b561b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"992db89fa1cb45ca9b09f837b8d4d048",
                  "label":"",
                  "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1127b3ae1de2408a9400695bd450ac96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7d804df7285b40e7bb911d23a3811efc",
                  "label":"",
                  "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c4451e75fbb4227b948fa6e453afa7c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"636acf13ec714cf3acc9280be6a368ac",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"50a8c0bbe5f84c0185cabe2660590e5e",
          "label":"投资项目",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":680},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"e69e54368c21479b8e087bd1839c0cdc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"71b303d4c87948df802efd838038e056",
                  "label":"",
                  "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":360,
                      "height":129},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4d070ec035d0490aab93a1d95f5f5e76",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":360,
                          "height":129},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u41.png"}},
{
                  "id":"a09b17df5d0a4937be3cd1b0758d7649",
                  "label":"",
                  "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc3ba43acfef4bccbfd08fe058741613",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"0740e16106b345868dd5bffb2fc03a0d",
                  "label":"",
                  "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a770c6bc03ad4962832d6a530db8b6b6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"62d1613a8fff462388f06cf7456d6b06",
                  "label":"",
                  "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"93c41859481c449487d89378ea5b8952",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"23b9253f025c43b0b0d5eb128f1716a2",
                  "label":"",
                  "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b59e58b3ff72429989f250c82ca0b3d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"50a8c0bbe5f84c0185cabe2660590e5e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"7141663f4fcc4889a24d351cea9b9357",
          "label":"投资项目",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":680},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3c0dcc0e4a0f4d2dba3a3aae74fdb6ab",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"937d65faa3a4493c8484859e008db12e",
                  "label":"",
                  "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":360,
                      "height":129},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"78847e96a3d84f288dce9d58bf001fcc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":360,
                          "height":129},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u41.png"}},
{
                  "id":"373e9edd454648b8b254087c635e9fbb",
                  "label":"",
                  "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdc1e299c59847d3b4fb1cca53d14c18",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"652d9081d85a434fad9ebfc6e4e3534c",
                  "label":"",
                  "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1129a3f7ca834e02a92eea212c3b9201",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2e9cd82e1001430cba5863b43e43c732",
                  "label":"",
                  "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad4c118785904fa5b9346a51b827355a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f65df29e7f1544b6a37cefe3feebdd60",
                  "label":"",
                  "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3f46027ac90941d4ba1a5550ed2fa14b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7141663f4fcc4889a24d351cea9b9357",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5e4ae18578f94d929ec9ba0decdcb4aa",
          "label":"钱包终端",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":340},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"596a6446ec5c426494271ca97af94b7c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aee3a9ae9d4b4f82af86639e7bca3681",
                  "label":"",
                  "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":360,
                      "height":129},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43e7be4ec2f54ab79b10a31a163edd1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":360,
                          "height":129},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u41.png"}},
{
                  "id":"2996df519f24462c905b468f05e267ed",
                  "label":"",
                  "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9bd76869b354372a8f279eb2558646e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"c2de7d695986430183a75b1c2beb4650",
                  "label":"",
                  "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8f14d4765644025a86bbfd84263e56d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"20f40b7e56d740838b76db4d61836d51",
                  "label":"",
                  "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":130},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec12d0a1b59f48078cb3370eb4c9f73c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":130},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2301b59902554962894dd7fec69c0986",
                  "label":"",
                  "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":130},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6163496f74884247813aae51103e378c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e4ae18578f94d929ec9ba0decdcb4aa",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":130},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"bc233ac147b944dab1cc26a469bf417a",
          "label":"钱包终端",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":340},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"5504188f10fe40f2a65d446260c8ddb6",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"ed0728465c904ff39cd3da4c81aa4fc5",
                  "label":"",
                  "parentDynamicPanel":"bc233ac147b944dab1cc26a469bf417a",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbc21f0bbfda45f6bbc673c10c8849be",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"bc233ac147b944dab1cc26a469bf417a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"d4a9634af5fc4dc2853ad049d8269736",
                  "label":"",
                  "parentDynamicPanel":"bc233ac147b944dab1cc26a469bf417a",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":7}},
                  "adaptiveStyles":{
},
                  "masterId":"a896b619ff1540af86d14c730330b6f6"}]}]},
{
          "id":"f7288edd95a94458b96f8676ac20782b",
          "label":"合规认证",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":340},
            "size":{
              "width":360,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"4f648a7a8d5a4afc989d1ca321fd8caa",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c632d72145cc4d2aaed1beef367398a5",
                  "label":"",
                  "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":360,
                      "height":129},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dad587f5786740cab582bc7ca9422aca",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":30},
                        "size":{
                          "width":360,
                          "height":129},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u41.png"}},
{
                  "id":"cf396fa6277841b5963a115b1228db5b",
                  "label":"",
                  "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9ea256d76b1414d83017bac6d7f9bde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"14d152e7604042528014e1be7033cd8c",
                  "label":"",
                  "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":7},
                    "size":{
                      "width":59,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08bd2984ce2f45c4bc99e216c3f650c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":7},
                        "size":{
                          "width":59,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6115f53ca28b4937a4e1d1d7727af9d1",
                  "label":"",
                  "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f891e1fa793e478daa7dd21748a09eec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":293,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e494684c71e24dca96c9ff00a26a5ef1",
                  "label":"",
                  "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":220,
                      "y":134},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe8765c6dcd947879512d4cb233f65c8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f7288edd95a94458b96f8676ac20782b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":220,
                          "y":134},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"1e2c180b61be462383f1ae5e27aa3dae",
          "label":"投资项目",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":510},
            "size":{
              "width":545,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1663099546f943fa9fe934b474d6d45c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4624c9259af94243ac688d72520f2a62",
                  "label":"",
                  "parentDynamicPanel":"1e2c180b61be462383f1ae5e27aa3dae",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f2d04ecb3d7a440189f876c72cfd9abe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1e2c180b61be462383f1ae5e27aa3dae",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"982e767790ba4426aab6a908bb109bd3",
                  "label":"",
                  "parentDynamicPanel":"1e2c180b61be462383f1ae5e27aa3dae",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":15}},
                  "adaptiveStyles":{
},
                  "masterId":"9920bb5158cd40438419d25318ae76ee"}]}]},
{
          "id":"6476c5d447e84f5a8dde89fab2d51e8f",
          "label":"投资项目",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":510},
            "size":{
              "width":545,
              "height":160}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"9f3cb510b6c149bab1752c1549bd9edb",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"019f569bf0b04ee0b7fe7754781d1f56",
                  "label":"",
                  "parentDynamicPanel":"6476c5d447e84f5a8dde89fab2d51e8f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":190,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4880fbad58e24cd4adface3185179374",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6476c5d447e84f5a8dde89fab2d51e8f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF000000,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "size":{
                          "width":190,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/solutions/u19.png"}},
{
                  "id":"08a8413b2a384f218f545f00aca1320b",
                  "label":"",
                  "parentDynamicPanel":"6476c5d447e84f5a8dde89fab2d51e8f",
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":15}},
                  "adaptiveStyles":{
},
                  "masterId":"9920bb5158cd40438419d25318ae76ee"}]}]}]}},
  "masters":{
    "a896b619ff1540af86d14c730330b6f6":{
      "packageId":"a896b619ff1540af86d14c730330b6f6",
      "type":"Axure:Master",
      "name":"3Q screen",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"04e5eba4ec734cde89907708fc91218b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":24},
              "size":{
                "width":360,
                "height":129},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7f89745015cc4d069fac571fec889318",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":24},
                  "size":{
                    "width":360,
                    "height":129},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/solutions/u41.png"}},
{
            "id":"a54d9399666a47228b27abb680e2d957",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":291,
                "y":0},
              "size":{
                "width":59,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"99bcfcfb440e405eaa38a95def32592b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":291,
                    "y":0},
                  "size":{
                    "width":59,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2d027864e4ae42ecba01e1b1a6385bb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":292,
                "y":123},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d319e71028b42f09de4ace7d837ead5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":292,
                    "y":123},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"fc0628d208d745468b1d7919b3f5ed92",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":220,
                "y":123},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"87e095fd15604553a614048632eea455",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":220,
                    "y":123},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "9920bb5158cd40438419d25318ae76ee":{
      "packageId":"9920bb5158cd40438419d25318ae76ee",
      "type":"Axure:Master",
      "name":"half screen",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ac1d2e500ddf4ab3ae6630d19ca00e53",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":16},
              "size":{
                "width":545,
                "height":129},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fb7db8c59e094735bb60812b8d6f863c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":16},
                  "size":{
                    "width":545,
                    "height":129},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/solutions/u111.png",
              "normal~":"images/solutions/u111.png"}},
{
            "id":"65fd07365b6441d0944177e71135ab26",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":486,
                "y":0},
              "size":{
                "width":59,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a5dc120593784bd5833c74c80efbe103",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":486,
                    "y":0},
                  "size":{
                    "width":59,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6a1d3e36b6fe48fe86fa0113aca06e37",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":467,
                "y":120},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b093cfe74d6c4c50940a9be7742f6ab3",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":467,
                    "y":120},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9e38533f5a9d4ef39773ca4fbce0d5bb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":394,
                "y":120},
              "size":{
                "width":53,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98f778de1ca546f6b509bbd3f5fcbfad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":394,
                    "y":120},
                  "size":{
                    "width":53,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2678c4a61b1e4756b85dbe96a383a8e9":{
      "scriptId":"u0"},
    "4b2164c08865404cbc00df5bf7c285cd":{
      "scriptId":"u1"},
    "00bbb9095cc843b0b1b88eb67da80f5c":{
      "scriptId":"u2"},
    "92e90a39d3f14186b3f278f94cd75f4f":{
      "scriptId":"u3"},
    "fbcae97b5a804716b2f49643a3afeb93":{
      "scriptId":"u4"},
    "932098d429774e839821543a20d6e5a7":{
      "scriptId":"u5"},
    "11737b436d3046d3ab1464ccfeb3ab1f":{
      "scriptId":"u6"},
    "571005b68afd41f88e83b96d6426b045":{
      "scriptId":"u7"},
    "fa9768880dc54530bc9a605cf070c611":{
      "scriptId":"u8"},
    "ab1dbb4fc2424cee8abda45b766bdab6":{
      "scriptId":"u9"},
    "fd26bd27579a41a48aee979d26f00592":{
      "scriptId":"u10"},
    "7e32d1edda144bfc8a3d46ee9e319f6a":{
      "scriptId":"u11"},
    "2e847cf2c8cf496aa5999bc03b703105":{
      "scriptId":"u12"},
    "0744357ebcdc45928cfdbba80ae4dedf":{
      "scriptId":"u13"},
    "4e1be3a7e23649c898ae5c5f61336e37":{
      "scriptId":"u14"},
    "26de0cef33704e5fbd73a29ea09d40dd":{
      "scriptId":"u15"},
    "3a6cf66dcf7a43f58b5d22aacc1fd47a":{
      "scriptId":"u16"},
    "a0983b2c96544318be377d29bd08af99":{
      "scriptId":"u17"},
    "2e82459d9a7f48cfa194d42db202c6e5":{
      "scriptId":"u18"},
    "84df29155f404e689241ce0c418eecdf":{
      "scriptId":"u19"},
    "cff95e496685487b8c8869f998ef63e6":{
      "scriptId":"u20"},
    "5f5f4170a0ea4086abc5ced9db9a54f9":{
      "scriptId":"u21"},
    "57accaa119de468887a4444f35d6ec89":{
      "scriptId":"u22"},
    "b5c7c9af5b914497b391bfdf6724662b":{
      "scriptId":"u23"},
    "f38d6be0e97540e69bf5b54e906ce176":{
      "scriptId":"u24"},
    "86aa7da0da224d1db4bb3e33a8c9054d":{
      "scriptId":"u25"},
    "aab96f05761748598b057a526f76d568":{
      "scriptId":"u26"},
    "7d68e11cddb24471a206a7d9f27e6aaf":{
      "scriptId":"u27"},
    "9739f36f734947f9bb94d0d20e0cb878":{
      "scriptId":"u28"},
    "7cb346b5e5a64c21b98fcbed9fba0a21":{
      "scriptId":"u29"},
    "d6efaccc0bc94fa09919103a3e2bcf79":{
      "scriptId":"u30"},
    "05a0229558de4c829c53ae97e0178144":{
      "scriptId":"u31"},
    "47cdaa26dbb440f586e4bc86f7d82bef":{
      "scriptId":"u32"},
    "df4e62b138fc4adaa432b371ee935130":{
      "scriptId":"u33"},
    "d2a99193a98347c39c68c67c0cd7c017":{
      "scriptId":"u34"},
    "1c0c335f1b24407eaade4e52ae343ab7":{
      "scriptId":"u35"},
    "26785c871a174a4b98821bafe65b4a15":{
      "scriptId":"u36"},
    "0d67ddb194dd4dfda9b1500e8d40c30e":{
      "scriptId":"u37"},
    "35a0094a1b1e458eb012e6c576163ff6":{
      "scriptId":"u38"},
    "06dae1aa71c14e1d9808e2b43e63f6e2":{
      "scriptId":"u39"},
    "636acf13ec714cf3acc9280be6a368ac":{
      "scriptId":"u40"},
    "937aec61d2844f6d9eb199c98843741d":{
      "scriptId":"u41"},
    "9767cee9e505495487164ec2b134e2fa":{
      "scriptId":"u42"},
    "a9da72997e69420a9b86de2002184b9f":{
      "scriptId":"u43"},
    "90caf53122d14bd5957fc8c0495f718a":{
      "scriptId":"u44"},
    "9653b81196944d9bb859feac1bc94353":{
      "scriptId":"u45"},
    "75da27d416f84387862facfe444b561b":{
      "scriptId":"u46"},
    "992db89fa1cb45ca9b09f837b8d4d048":{
      "scriptId":"u47"},
    "1127b3ae1de2408a9400695bd450ac96":{
      "scriptId":"u48"},
    "7d804df7285b40e7bb911d23a3811efc":{
      "scriptId":"u49"},
    "4c4451e75fbb4227b948fa6e453afa7c":{
      "scriptId":"u50"},
    "50a8c0bbe5f84c0185cabe2660590e5e":{
      "scriptId":"u51"},
    "71b303d4c87948df802efd838038e056":{
      "scriptId":"u52"},
    "4d070ec035d0490aab93a1d95f5f5e76":{
      "scriptId":"u53"},
    "a09b17df5d0a4937be3cd1b0758d7649":{
      "scriptId":"u54"},
    "cc3ba43acfef4bccbfd08fe058741613":{
      "scriptId":"u55"},
    "0740e16106b345868dd5bffb2fc03a0d":{
      "scriptId":"u56"},
    "a770c6bc03ad4962832d6a530db8b6b6":{
      "scriptId":"u57"},
    "62d1613a8fff462388f06cf7456d6b06":{
      "scriptId":"u58"},
    "93c41859481c449487d89378ea5b8952":{
      "scriptId":"u59"},
    "23b9253f025c43b0b0d5eb128f1716a2":{
      "scriptId":"u60"},
    "b59e58b3ff72429989f250c82ca0b3d2":{
      "scriptId":"u61"},
    "7141663f4fcc4889a24d351cea9b9357":{
      "scriptId":"u62"},
    "937d65faa3a4493c8484859e008db12e":{
      "scriptId":"u63"},
    "78847e96a3d84f288dce9d58bf001fcc":{
      "scriptId":"u64"},
    "373e9edd454648b8b254087c635e9fbb":{
      "scriptId":"u65"},
    "bdc1e299c59847d3b4fb1cca53d14c18":{
      "scriptId":"u66"},
    "652d9081d85a434fad9ebfc6e4e3534c":{
      "scriptId":"u67"},
    "1129a3f7ca834e02a92eea212c3b9201":{
      "scriptId":"u68"},
    "2e9cd82e1001430cba5863b43e43c732":{
      "scriptId":"u69"},
    "ad4c118785904fa5b9346a51b827355a":{
      "scriptId":"u70"},
    "f65df29e7f1544b6a37cefe3feebdd60":{
      "scriptId":"u71"},
    "3f46027ac90941d4ba1a5550ed2fa14b":{
      "scriptId":"u72"},
    "5e4ae18578f94d929ec9ba0decdcb4aa":{
      "scriptId":"u73"},
    "aee3a9ae9d4b4f82af86639e7bca3681":{
      "scriptId":"u74"},
    "43e7be4ec2f54ab79b10a31a163edd1a":{
      "scriptId":"u75"},
    "2996df519f24462c905b468f05e267ed":{
      "scriptId":"u76"},
    "b9bd76869b354372a8f279eb2558646e":{
      "scriptId":"u77"},
    "c2de7d695986430183a75b1c2beb4650":{
      "scriptId":"u78"},
    "e8f14d4765644025a86bbfd84263e56d":{
      "scriptId":"u79"},
    "20f40b7e56d740838b76db4d61836d51":{
      "scriptId":"u80"},
    "ec12d0a1b59f48078cb3370eb4c9f73c":{
      "scriptId":"u81"},
    "2301b59902554962894dd7fec69c0986":{
      "scriptId":"u82"},
    "6163496f74884247813aae51103e378c":{
      "scriptId":"u83"},
    "bc233ac147b944dab1cc26a469bf417a":{
      "scriptId":"u84"},
    "ed0728465c904ff39cd3da4c81aa4fc5":{
      "scriptId":"u85"},
    "bbc21f0bbfda45f6bbc673c10c8849be":{
      "scriptId":"u86"},
    "d4a9634af5fc4dc2853ad049d8269736":{
      "scriptId":"u87",
      "04e5eba4ec734cde89907708fc91218b":{
        "scriptId":"u88"},
      "7f89745015cc4d069fac571fec889318":{
        "scriptId":"u89"},
      "a54d9399666a47228b27abb680e2d957":{
        "scriptId":"u90"},
      "99bcfcfb440e405eaa38a95def32592b":{
        "scriptId":"u91"},
      "2d027864e4ae42ecba01e1b1a6385bb6":{
        "scriptId":"u92"},
      "0d319e71028b42f09de4ace7d837ead5":{
        "scriptId":"u93"},
      "fc0628d208d745468b1d7919b3f5ed92":{
        "scriptId":"u94"},
      "87e095fd15604553a614048632eea455":{
        "scriptId":"u95"}},
    "f7288edd95a94458b96f8676ac20782b":{
      "scriptId":"u96"},
    "c632d72145cc4d2aaed1beef367398a5":{
      "scriptId":"u97"},
    "dad587f5786740cab582bc7ca9422aca":{
      "scriptId":"u98"},
    "cf396fa6277841b5963a115b1228db5b":{
      "scriptId":"u99"},
    "d9ea256d76b1414d83017bac6d7f9bde":{
      "scriptId":"u100"},
    "14d152e7604042528014e1be7033cd8c":{
      "scriptId":"u101"},
    "08bd2984ce2f45c4bc99e216c3f650c8":{
      "scriptId":"u102"},
    "6115f53ca28b4937a4e1d1d7727af9d1":{
      "scriptId":"u103"},
    "f891e1fa793e478daa7dd21748a09eec":{
      "scriptId":"u104"},
    "e494684c71e24dca96c9ff00a26a5ef1":{
      "scriptId":"u105"},
    "fe8765c6dcd947879512d4cb233f65c8":{
      "scriptId":"u106"},
    "1e2c180b61be462383f1ae5e27aa3dae":{
      "scriptId":"u107"},
    "4624c9259af94243ac688d72520f2a62":{
      "scriptId":"u108"},
    "f2d04ecb3d7a440189f876c72cfd9abe":{
      "scriptId":"u109"},
    "982e767790ba4426aab6a908bb109bd3":{
      "scriptId":"u110",
      "ac1d2e500ddf4ab3ae6630d19ca00e53":{
        "scriptId":"u111"},
      "fb7db8c59e094735bb60812b8d6f863c":{
        "scriptId":"u112"},
      "65fd07365b6441d0944177e71135ab26":{
        "scriptId":"u113"},
      "a5dc120593784bd5833c74c80efbe103":{
        "scriptId":"u114"},
      "6a1d3e36b6fe48fe86fa0113aca06e37":{
        "scriptId":"u115"},
      "b093cfe74d6c4c50940a9be7742f6ab3":{
        "scriptId":"u116"},
      "9e38533f5a9d4ef39773ca4fbce0d5bb":{
        "scriptId":"u117"},
      "98f778de1ca546f6b509bbd3f5fcbfad":{
        "scriptId":"u118"}},
    "6476c5d447e84f5a8dde89fab2d51e8f":{
      "scriptId":"u119"},
    "019f569bf0b04ee0b7fe7754781d1f56":{
      "scriptId":"u120"},
    "4880fbad58e24cd4adface3185179374":{
      "scriptId":"u121"},
    "08a8413b2a384f218f545f00aca1320b":{
      "scriptId":"u122",
      "ac1d2e500ddf4ab3ae6630d19ca00e53":{
        "scriptId":"u123"},
      "fb7db8c59e094735bb60812b8d6f863c":{
        "scriptId":"u124"},
      "65fd07365b6441d0944177e71135ab26":{
        "scriptId":"u125"},
      "a5dc120593784bd5833c74c80efbe103":{
        "scriptId":"u126"},
      "6a1d3e36b6fe48fe86fa0113aca06e37":{
        "scriptId":"u127"},
      "b093cfe74d6c4c50940a9be7742f6ab3":{
        "scriptId":"u128"},
      "9e38533f5a9d4ef39773ca4fbce0d5bb":{
        "scriptId":"u129"},
      "98f778de1ca546f6b509bbd3f5fcbfad":{
        "scriptId":"u130"}}}});