$axure.loadCurrentPage({
  "url":"创建账户.html",
  "generationDate":new Date(1482495099265.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d06459fcb0e14b0d8e3b4cd5b86e5bf6",
    "type":"Axure:Page",
    "name":"创建账户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7d6eb8db3ebf41d1ae359f47e3cdcb9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":7,
              "y":3},
            "size":{
              "width":185,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e584c62bbcc46a9a41c29202d1a310c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":7,
                  "y":3},
                "size":{
                  "width":185,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e3cea3cef9448e591252c2e4b03126f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":84},
            "size":{
              "width":790,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf6242765d224ef5b5c6ef32e488c5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":84},
                "size":{
                  "width":790,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed0cf05f07bd41bda590e68098384cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":112,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9668ede191c84e46843e86ea330667a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":112,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5bf9cf8e87a4763a09d48b22edb70bb",
          "label":"k1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":110},
            "size":{
              "width":800,
              "height":170}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"0c7a88b5dc7c45b29760ad109d8578b1",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"de5e37f63c454e958f3c2a35d6d9de87",
                  "label":"",
                  "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":60},
                    "size":{
                      "width":739,
                      "height":72}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cb01de5878ea45edae2454f2ebab5963",
                      "label":"",
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "size":{
                          "width":95,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"c0b8fbcaa49a4b6fb30f151091363de7",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontSize":"16px",
                            "fontWeight":"700",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "size":{
                              "width":95,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u8.png"}},
{
                      "id":"ed4d26ae6aa04a689fe8a59edae99149",
                      "label":"",
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":0,
                          "y":36},
                        "size":{
                          "width":95,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"5b85845e968d45d0acd331f1c9d5b2a5",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "fontName":"'Arial Negreta', 'Arial'",
                            "fontSize":"16px",
                            "fontWeight":"700",
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":0,
                              "y":36},
                            "size":{
                              "width":95,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u12.png"}},
{
                      "id":"74568ae8af604408a9ee712a4084efd9",
                      "label":"",
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":95,
                          "y":0},
                        "size":{
                          "width":644,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"12165b55771b47f79ebd5d82b22dac28",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":95,
                              "y":0},
                            "size":{
                              "width":644,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u10.png"}},
{
                      "id":"9878e95a544c4e178131780fe413b644",
                      "label":"",
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":95,
                          "y":36},
                        "size":{
                          "width":644,
                          "height":36}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"7e793b7f37bc41df8e87e89cf263fa94",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "location":{
                              "x":95,
                              "y":36},
                            "size":{
                              "width":644,
                              "height":36}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u14.png"}}]},
{
                  "id":"bdb7ba4de97d4903b82638aa950b3c4b",
                  "label":"",
                  "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF},
                    "location":{
                      "x":30,
                      "y":10},
                    "size":{
                      "width":150,
                      "height":40},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16d374f2a8b041478b6d0a458979a385",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF0099FF},
                        "location":{
                          "x":30,
                          "y":10},
                        "size":{
                          "width":150,
                          "height":40},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建账户/u16.png"}},
{
                  "id":"7aa3eb46b80540f3aae27027ff863877",
                  "label":"",
                  "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":144},
                    "size":{
                      "width":739,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"adde6750746a4b148d873d54ef0632a7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e5bf9cf8e87a4763a09d48b22edb70bb",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":144},
                        "size":{
                          "width":739,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"102e3d87a0984b6a9b3e10b1c71ac39f",
          "label":"k2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":310},
            "size":{
              "width":800,
              "height":190}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"3b773aa2162c4d86bbeddc3086a71a63",
              "label":"默认",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"678620a7335a46c4b964c6b07991e7d8",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":80},
                    "size":{
                      "width":730,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"267713b5314747ce894997ec7d29a380",
                      "label":"",
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"middle",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "size":{
                          "width":730,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"8e5f6886c6dd4d31ba349e02a99d2ec5",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "verticalAlignment":"middle",
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "size":{
                              "width":730,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u22.png"}}]},
{
                  "id":"ec330c4d1770491ab06523149a721661",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":30,
                      "y":120},
                    "size":{
                      "width":220,
                      "height":40},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2576ba5688343b7a9aa906484a0bada",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":30,
                          "y":120},
                        "size":{
                          "width":220,
                          "height":40},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建账户/u24.png"}},
{
                  "id":"e79da0a74ad6474a859c8d1f9f96c857",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":44},
                    "size":{
                      "width":790,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a0993b5f25c0486cab1e272f371278dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":44},
                        "size":{
                          "width":790,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f0b324508e024250b38db72c59ee76e0",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":112,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe50454939924e908357c29101127d16",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":112,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"80f1213a03924bf1874be71ab0a16cd3",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":132,
                      "y":15},
                    "size":{
                      "width":392,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5ad30eeca37b45f2a94d0f684e21861b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":132,
                          "y":15},
                        "size":{
                          "width":392,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"2e7a4138c36b4fda8d870a53250874f4",
              "label":"输入",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"21ab8630fb2940b29e23f3baa0675b3b",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":80},
                    "size":{
                      "width":730,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"17bef1b907424b72a98dd65d326c4ccb",
                      "label":"",
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "size":{
                          "width":730,
                          "height":30}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"d539b116bb2c424a8de2553b05195827",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "size":{
                              "width":730,
                              "height":30}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u22.png"}}]},
{
                  "id":"fe0c3aab0de04f16a1cb0a3926b69540",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":112,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3a6718467a674b60badf3b1b1561e3c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":112,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"79049dc00a454498965ffe677462a9ea",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":30,
                      "y":120},
                    "size":{
                      "width":220,
                      "height":40},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc12ba392f2c4c8488b8d928872e8dad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "location":{
                          "x":30,
                          "y":120},
                        "size":{
                          "width":220,
                          "height":40},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/创建账户/u24.png"}},
{
                  "id":"96ee5f44034f4766a2f9cbaae368937d",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":30,
                      "y":44},
                    "size":{
                      "width":790,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a55f48cba8240c09b9be70078dd320e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":30,
                          "y":44},
                        "size":{
                          "width":790,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3076c74ebec043429eccdcce5862c8c2",
                  "label":"",
                  "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "location":{
                      "x":132,
                      "y":15},
                    "size":{
                      "width":392,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df863ef2c1014dbeb43962db64325d1a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"102e3d87a0984b6a9b3e10b1c71ac39f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "location":{
                          "x":132,
                          "y":15},
                        "size":{
                          "width":392,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
          "label":"k3",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":510},
            "size":{
              "width":800,
              "height":60}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"104fbf42e8504ee58133b603f135daf9",
              "label":"成功",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9f9a67f3049b4516a6f820641c55a112",
                  "label":"",
                  "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":730,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd60cbc0217a4410abc08d88237ceef7",
                      "label":"",
                      "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFDEEEF1},
                        "size":{
                          "width":730,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF006600}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"32726e6f0e11424cbae269c84652a78a",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFDEEEF1},
                            "size":{
                              "width":730,
                              "height":36},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFF006600}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u45.png"}}]}]},
{
              "id":"003bb23bbf714172977027a34670fbbf",
              "label":"失败",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"4a43d1664c6e491c8693f936a29d284d",
                  "label":"",
                  "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                  "type":"table",
                  "styleType":"table",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":730,
                      "height":36}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f59f7271c5342aebc219f4461a975be",
                      "label":"",
                      "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                      "type":"tableCell",
                      "styleType":"tableCell",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFCCFF},
                        "size":{
                          "width":730,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFF3300}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a88e648af874445d941a065a75ec970c",
                          "label":"",
                          "isContained":true,
                          "parentDynamicPanel":"bd5c3bdeb1dd4614b5e7b5ae881909f8",
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"center",
                            "verticalAlignment":"middle",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFFFCCFF},
                            "size":{
                              "width":730,
                              "height":36},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFFF3300}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"images/创建账户/u48.png"}}]}]}]},
{
          "id":"55819ff95751400396b5a6a611cc03ac",
          "label":"f2",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":570},
            "size":{
              "width":800,
              "height":430}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "7d6eb8db3ebf41d1ae359f47e3cdcb9c":{
      "scriptId":"u0"},
    "6e584c62bbcc46a9a41c29202d1a310c":{
      "scriptId":"u1"},
    "4e3cea3cef9448e591252c2e4b03126f":{
      "scriptId":"u2"},
    "cf6242765d224ef5b5c6ef32e488c5d7":{
      "scriptId":"u3"},
    "ed0cf05f07bd41bda590e68098384cb2":{
      "scriptId":"u4"},
    "9668ede191c84e46843e86ea330667a7":{
      "scriptId":"u5"},
    "e5bf9cf8e87a4763a09d48b22edb70bb":{
      "scriptId":"u6"},
    "de5e37f63c454e958f3c2a35d6d9de87":{
      "scriptId":"u7"},
    "cb01de5878ea45edae2454f2ebab5963":{
      "scriptId":"u8"},
    "c0b8fbcaa49a4b6fb30f151091363de7":{
      "scriptId":"u9"},
    "74568ae8af604408a9ee712a4084efd9":{
      "scriptId":"u10"},
    "12165b55771b47f79ebd5d82b22dac28":{
      "scriptId":"u11"},
    "ed4d26ae6aa04a689fe8a59edae99149":{
      "scriptId":"u12"},
    "5b85845e968d45d0acd331f1c9d5b2a5":{
      "scriptId":"u13"},
    "9878e95a544c4e178131780fe413b644":{
      "scriptId":"u14"},
    "7e793b7f37bc41df8e87e89cf263fa94":{
      "scriptId":"u15"},
    "bdb7ba4de97d4903b82638aa950b3c4b":{
      "scriptId":"u16"},
    "16d374f2a8b041478b6d0a458979a385":{
      "scriptId":"u17"},
    "7aa3eb46b80540f3aae27027ff863877":{
      "scriptId":"u18"},
    "adde6750746a4b148d873d54ef0632a7":{
      "scriptId":"u19"},
    "102e3d87a0984b6a9b3e10b1c71ac39f":{
      "scriptId":"u20"},
    "678620a7335a46c4b964c6b07991e7d8":{
      "scriptId":"u21"},
    "267713b5314747ce894997ec7d29a380":{
      "scriptId":"u22"},
    "8e5f6886c6dd4d31ba349e02a99d2ec5":{
      "scriptId":"u23"},
    "ec330c4d1770491ab06523149a721661":{
      "scriptId":"u24"},
    "b2576ba5688343b7a9aa906484a0bada":{
      "scriptId":"u25"},
    "e79da0a74ad6474a859c8d1f9f96c857":{
      "scriptId":"u26"},
    "a0993b5f25c0486cab1e272f371278dd":{
      "scriptId":"u27"},
    "f0b324508e024250b38db72c59ee76e0":{
      "scriptId":"u28"},
    "fe50454939924e908357c29101127d16":{
      "scriptId":"u29"},
    "80f1213a03924bf1874be71ab0a16cd3":{
      "scriptId":"u30"},
    "5ad30eeca37b45f2a94d0f684e21861b":{
      "scriptId":"u31"},
    "21ab8630fb2940b29e23f3baa0675b3b":{
      "scriptId":"u32"},
    "17bef1b907424b72a98dd65d326c4ccb":{
      "scriptId":"u33"},
    "d539b116bb2c424a8de2553b05195827":{
      "scriptId":"u34"},
    "fe0c3aab0de04f16a1cb0a3926b69540":{
      "scriptId":"u35"},
    "3a6718467a674b60badf3b1b1561e3c6":{
      "scriptId":"u36"},
    "79049dc00a454498965ffe677462a9ea":{
      "scriptId":"u37"},
    "cc12ba392f2c4c8488b8d928872e8dad":{
      "scriptId":"u38"},
    "96ee5f44034f4766a2f9cbaae368937d":{
      "scriptId":"u39"},
    "0a55f48cba8240c09b9be70078dd320e":{
      "scriptId":"u40"},
    "3076c74ebec043429eccdcce5862c8c2":{
      "scriptId":"u41"},
    "df863ef2c1014dbeb43962db64325d1a":{
      "scriptId":"u42"},
    "bd5c3bdeb1dd4614b5e7b5ae881909f8":{
      "scriptId":"u43"},
    "9f9a67f3049b4516a6f820641c55a112":{
      "scriptId":"u44"},
    "fd60cbc0217a4410abc08d88237ceef7":{
      "scriptId":"u45"},
    "32726e6f0e11424cbae269c84652a78a":{
      "scriptId":"u46"},
    "4a43d1664c6e491c8693f936a29d284d":{
      "scriptId":"u47"},
    "4f59f7271c5342aebc219f4461a975be":{
      "scriptId":"u48"},
    "a88e648af874445d941a065a75ec970c":{
      "scriptId":"u49"},
    "55819ff95751400396b5a6a611cc03ac":{
      "scriptId":"u50"}}});