$axure.loadCurrentPage({
  "url":"返回源码.html",
  "generationDate":new Date(1482495099302.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"875cfc6d9c244bba80716500db0bb82e",
    "type":"Axure:Page",
    "name":"返回源码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFF2F2F2},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e2020a1bd3714d36989636a9de8804fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "size":{
              "width":800,
              "height":336}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7300113a8bb641308dc17c6bd10172b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":800,
                  "height":336}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "e2020a1bd3714d36989636a9de8804fe":{
      "scriptId":"u0"},
    "7300113a8bb641308dc17c6bd10172b4":{
      "scriptId":"u1"}}});