$axure.loadCurrentPage({
  "url":"简介.html",
  "generationDate":new Date(1482495099105.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9a753fc7360f441ba7f0b369ef0e3f94",
    "type":"Axure:Page",
    "name":"简介",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5d8f71940abf4f0fbc6acd0bd33c37e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":7,
              "y":3},
            "size":{
              "width":149,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f592cf68f7a74bfa8f15f3f9459a2ca6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":7,
                  "y":3},
                "size":{
                  "width":149,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a99424933d584c32a3ed0a40ae428327",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":386,
              "y":44},
            "size":{
              "width":78,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ac473186f31421ab128ef45e81e7855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":386,
                  "y":44},
                "size":{
                  "width":78,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u5.png",
            "selected~":"images/lefinshare/u5_selected.png",
            "mouseOver~":"images/lefinshare/u5_mouseOver.png",
            "mouseDown~":"images/lefinshare/u5_mouseOver.png",
            "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
          "id":"a838c81899cc4db99b2e8be3c86eec3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":130,
              "y":44},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c7a6d74eddc4ff689b082533c22ffcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":130,
                  "y":44},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/lefinshare/u7_selected.png",
            "mouseOver~":"images/lefinshare/u7_mouseOver.png",
            "mouseDown~":"images/lefinshare/u7_mouseOver.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"f6344e04e6f94aeca8c541d381aff028",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":472,
              "y":44},
            "size":{
              "width":78,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40f6594801044f28c5852e838bfac90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":472,
                  "y":44},
                "size":{
                  "width":78,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u5.png",
            "selected~":"images/lefinshare/u5_selected.png",
            "mouseOver~":"images/lefinshare/u5_mouseOver.png",
            "mouseDown~":"images/lefinshare/u5_mouseOver.png",
            "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
          "id":"028b2999d03942aab4204c671e069aee",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":557,
              "y":44},
            "size":{
              "width":78,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72a1d8c24dd34fa29071260486b8ed6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":557,
                  "y":44},
                "size":{
                  "width":78,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u5.png",
            "selected~":"images/lefinshare/u5_selected.png",
            "mouseOver~":"images/lefinshare/u5_mouseOver.png",
            "mouseDown~":"images/lefinshare/u5_mouseOver.png",
            "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
          "id":"9d82d40133d44107a886bd9e1262a648",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":642,
              "y":44},
            "size":{
              "width":78,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"edbc26190fee44ffa2d69602ec7e66e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":642,
                  "y":44},
                "size":{
                  "width":78,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u5.png",
            "selected~":"images/lefinshare/u5_selected.png",
            "mouseOver~":"images/lefinshare/u5_mouseOver.png",
            "mouseDown~":"images/lefinshare/u5_mouseOver.png",
            "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
          "id":"fb3d4ac8636f429b941d842bd1c4e818",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":730,
              "y":44},
            "size":{
              "width":148,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2488219c3c149e583e8ef7f318195f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":730,
                  "y":44},
                "size":{
                  "width":148,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u15.png",
            "selected~":"images/lefinshare/u15_selected.png",
            "mouseOver~":"images/lefinshare/u15_mouseOver.png",
            "mouseDown~":"images/lefinshare/u15_mouseOver.png",
            "disabled~":"images/lefinshare/u15_mouseOver.png"}},
{
          "id":"7ebb5e497d2a4e8baa8e29ecbd8617d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":7,
              "y":124},
            "size":{
              "width":1131,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6a385f9cc9c44a283abb3dfb365df67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":7,
                  "y":124},
                "size":{
                  "width":1131,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u53.png"}},
{
          "id":"8b5f13fbbc86435fb5aed437fd3d2147",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":20,
              "y":44},
            "size":{
              "width":100,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f017c7a71fd74110b47607501a6dea68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":20,
                  "y":44},
                "size":{
                  "width":100,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u7.png",
            "selected~":"images/lefinshare/u7_selected.png",
            "mouseOver~":"images/lefinshare/u7_mouseOver.png",
            "mouseDown~":"images/lefinshare/u7_mouseOver.png",
            "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
          "id":"0efc46c29d6047719d64c8354ae264fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":240,
              "y":44},
            "size":{
              "width":136,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"730afca8e0514d26970de1a3ab9b61aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":240,
                  "y":44},
                "size":{
                  "width":136,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u19.png",
            "selected~":"images/lefinshare/u19_selected.png",
            "mouseOver~":"images/lefinshare/u19_mouseOver.png",
            "mouseDown~":"images/lefinshare/u19_mouseOver.png",
            "disabled~":"images/lefinshare/u19_mouseOver.png"}},
{
          "id":"eb0d9327d2014b4ca673fc12804d4840",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":23,
              "y":110},
            "size":{
              "width":372,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb16227d814145c1afdce4adf2b547ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":23,
                  "y":110},
                "size":{
                  "width":372,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实验室",
                      "target":{
                        "targetType":"page",
                        "url":"实验室.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2f558d417ba4a8d92e7bfb932651047",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":23,
              "y":144},
            "size":{
              "width":377,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"667b81db692c408a9f13dfbf293f86e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":23,
                  "y":144},
                "size":{
                  "width":377,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0dcf2390e06e4ae5aecf3e53ddf81a2f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":690},
            "size":{
              "width":87,
              "height":50},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"470555c87fb04a749f55a707a6dc63bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":357,
                  "y":690},
                "size":{
                  "width":87,
                  "height":50},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/absstellar/u20.png"}},
{
          "id":"4fe4d64ff7bf43228a18b47b77760b2e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":701},
            "size":{
              "width":260,
              "height":31},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91ed57a1044d448b9b96b13479d59781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":447,
                  "y":701},
                "size":{
                  "width":260,
                  "height":31},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/absstellar/u22.png"}},
{
          "id":"d6c15f12dd9a4a129c2250c98d753bb2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":765,
              "y":624},
            "size":{
              "width":335,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad07e524578246a08778f3b19e5c4625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":765,
                  "y":624},
                "size":{
                  "width":335,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u61.png"}},
{
          "id":"ff0e2a01db0a4362815f32061d6bed39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":343,
              "y":614},
            "size":{
              "width":360,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f9a5e793904811be7b70c143521dec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":343,
                  "y":614},
                "size":{
                  "width":360,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u57.png"}},
{
          "id":"03b3b45c6d304ead90d7f78aaa9a62d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":17,
              "y":604},
            "size":{
              "width":262,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b5f5356044047a19225ce7691fbe673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":17,
                  "y":604},
                "size":{
                  "width":262,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u59.png"}},
{
          "id":"cd28f469abd848a19bbbcf285b58b2f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":717,
              "y":708},
            "size":{
              "width":383,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f39a843ff2e4e0188050e592d7c719f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":717,
                  "y":708},
                "size":{
                  "width":383,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"51c71dd2d3fb4cb689147184f1410c9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":888,
              "y":44},
            "size":{
              "width":110,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd63ef4050cf4f2bbd0a4fbe37c6ab15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":888,
                  "y":44},
                "size":{
                  "width":110,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u21.png",
            "selected~":"images/lefinshare/u21_selected.png",
            "mouseOver~":"images/lefinshare/u21_mouseOver.png",
            "mouseDown~":"images/lefinshare/u21_mouseOver.png",
            "disabled~":"images/lefinshare/u21_mouseOver.png"}},
{
          "id":"3286387091f740499c53535788e891d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "disabled":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}}},
            "location":{
              "x":1008,
              "y":44},
            "size":{
              "width":110,
              "height":40},
            "cornerRadiusTopLeft":"34"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f3f835d38f444c88eae8953d8a7788e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099FF}},
                  "disabled":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}}},
                "location":{
                  "x":1008,
                  "y":44},
                "size":{
                  "width":110,
                  "height":40},
                "cornerRadiusTopLeft":"34"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u21.png",
            "selected~":"images/lefinshare/u21_selected.png",
            "mouseOver~":"images/lefinshare/u21_mouseOver.png",
            "mouseDown~":"images/lefinshare/u21_mouseOver.png",
            "disabled~":"images/lefinshare/u21_mouseOver.png"}},
{
          "id":"cf71cd1dea94466caf23bc69eddf8b70",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":701},
            "size":{
              "width":150,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f266a41fc77e42e8b2cd3fd0a0cad34a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":701},
                "size":{
                  "width":150,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u0.png"}},
{
          "id":"966fa2f084f94d2cb160a8e43ec7241d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":708},
            "size":{
              "width":80,
              "height":24},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb267c0aa5114ea188d27cc93ed7486d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":708},
                "size":{
                  "width":80,
                  "height":24},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5d8f71940abf4f0fbc6acd0bd33c37e3":{
      "scriptId":"u0"},
    "f592cf68f7a74bfa8f15f3f9459a2ca6":{
      "scriptId":"u1"},
    "a99424933d584c32a3ed0a40ae428327":{
      "scriptId":"u2"},
    "5ac473186f31421ab128ef45e81e7855":{
      "scriptId":"u3"},
    "a838c81899cc4db99b2e8be3c86eec3f":{
      "scriptId":"u4"},
    "0c7a6d74eddc4ff689b082533c22ffcc":{
      "scriptId":"u5"},
    "f6344e04e6f94aeca8c541d381aff028":{
      "scriptId":"u6"},
    "e40f6594801044f28c5852e838bfac90":{
      "scriptId":"u7"},
    "028b2999d03942aab4204c671e069aee":{
      "scriptId":"u8"},
    "72a1d8c24dd34fa29071260486b8ed6f":{
      "scriptId":"u9"},
    "9d82d40133d44107a886bd9e1262a648":{
      "scriptId":"u10"},
    "edbc26190fee44ffa2d69602ec7e66e1":{
      "scriptId":"u11"},
    "fb3d4ac8636f429b941d842bd1c4e818":{
      "scriptId":"u12"},
    "b2488219c3c149e583e8ef7f318195f5":{
      "scriptId":"u13"},
    "7ebb5e497d2a4e8baa8e29ecbd8617d2":{
      "scriptId":"u14"},
    "b6a385f9cc9c44a283abb3dfb365df67":{
      "scriptId":"u15"},
    "8b5f13fbbc86435fb5aed437fd3d2147":{
      "scriptId":"u16"},
    "f017c7a71fd74110b47607501a6dea68":{
      "scriptId":"u17"},
    "0efc46c29d6047719d64c8354ae264fb":{
      "scriptId":"u18"},
    "730afca8e0514d26970de1a3ab9b61aa":{
      "scriptId":"u19"},
    "eb0d9327d2014b4ca673fc12804d4840":{
      "scriptId":"u20"},
    "bb16227d814145c1afdce4adf2b547ff":{
      "scriptId":"u21"},
    "f2f558d417ba4a8d92e7bfb932651047":{
      "scriptId":"u22"},
    "667b81db692c408a9f13dfbf293f86e7":{
      "scriptId":"u23"},
    "0dcf2390e06e4ae5aecf3e53ddf81a2f":{
      "scriptId":"u24"},
    "470555c87fb04a749f55a707a6dc63bd":{
      "scriptId":"u25"},
    "4fe4d64ff7bf43228a18b47b77760b2e":{
      "scriptId":"u26"},
    "91ed57a1044d448b9b96b13479d59781":{
      "scriptId":"u27"},
    "d6c15f12dd9a4a129c2250c98d753bb2":{
      "scriptId":"u28"},
    "ad07e524578246a08778f3b19e5c4625":{
      "scriptId":"u29"},
    "ff0e2a01db0a4362815f32061d6bed39":{
      "scriptId":"u30"},
    "31f9a5e793904811be7b70c143521dec":{
      "scriptId":"u31"},
    "03b3b45c6d304ead90d7f78aaa9a62d6":{
      "scriptId":"u32"},
    "9b5f5356044047a19225ce7691fbe673":{
      "scriptId":"u33"},
    "cd28f469abd848a19bbbcf285b58b2f7":{
      "scriptId":"u34"},
    "4f39a843ff2e4e0188050e592d7c719f":{
      "scriptId":"u35"},
    "51c71dd2d3fb4cb689147184f1410c9c":{
      "scriptId":"u36"},
    "bd63ef4050cf4f2bbd0a4fbe37c6ab15":{
      "scriptId":"u37"},
    "3286387091f740499c53535788e891d7":{
      "scriptId":"u38"},
    "3f3f835d38f444c88eae8953d8a7788e":{
      "scriptId":"u39"},
    "cf71cd1dea94466caf23bc69eddf8b70":{
      "scriptId":"u40"},
    "f266a41fc77e42e8b2cd3fd0a0cad34a":{
      "scriptId":"u41"},
    "966fa2f084f94d2cb160a8e43ec7241d":{
      "scriptId":"u42"},
    "eb267c0aa5114ea188d27cc93ed7486d":{
      "scriptId":"u43"}}});