$axure.loadCurrentPage({
  "url":"oldhome.html",
  "generationDate":new Date(1482495098570.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e200feb5e79646358ffa998a8ca97065",
    "type":"Axure:Page",
    "name":"OLDHome",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"44c00c895dd54c3882145e13f8a97937",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":408},
            "size":{
              "width":1131,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d913d3a6fd43b49dbab0b9b6361f8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":408},
                "size":{
                  "width":1131,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u53.png"}},
{
          "id":"e90307c439d84103a6052cf76135310e",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":0},
            "size":{
              "width":580,
              "height":48},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49416dc552344a61a5650f196ebcefad",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":580,
                  "height":48}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bef698bfd60d40bba1d835f75f482b3d",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"135e51e49f5d44e6aba724490fc74b01",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 http://150.242.56.116",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"http://150.242.56.116",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4da55bf2fdba4795abf57ccf3b3b0c6a",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef109a31bf3d41daa2213fe9a9dfd61c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"03e4bbffecc7410ba675f34f99b13b5f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":340,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"16208100b0d44b1eb7735e1781ba1b43",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":340,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eb6c598b415540acbc4a23985f67735f",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1d7acd4c1dd423593019052c6845161",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":420,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"a4845d550dac4f66bce1a8d536668ae4",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"33429bd6429d4007b6b97469f09a3079",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7918b95f50154205944e992756969934",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":180,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":48},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eecdff85f4db4be69c7d5228e2452311",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":180,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":48},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"23704915e3b44135b0a5c253cfd80b89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":15},
            "size":{
              "width":178,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d83de9b0495c4624864584cf7760421d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":15},
                "size":{
                  "width":178,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c91ce1aaf1114a16ae2c30121223dfa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":26,
              "y":156},
            "size":{
              "width":372,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5605babd159432785490eca8d7211dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":26,
                  "y":156},
                "size":{
                  "width":372,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实验室",
                      "target":{
                        "targetType":"page",
                        "url":"实验室.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7381274234c49a9ad1a220106791752",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":26,
              "y":190},
            "size":{
              "width":377,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60469e2ff18e42b19fce324843fe6052",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":26,
                  "y":190},
                "size":{
                  "width":377,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c2084d40d7d4344acad2a1dc0c1f8e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":720,
              "y":374},
            "size":{
              "width":383,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"265d038c5d5541178998cb19409d8a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":720,
                  "y":374},
                "size":{
                  "width":383,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06f5f1515a824bff96584264a321ce94",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":489.5,
              "y":213},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9249b59589b9419f95dae4042c559c3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":489.5,
                  "y":213},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d58fb5471004ea0a939ec243cf3d533",
          "label":"topcampaints",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":0},
            "size":{
              "width":375,
              "height":100}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"wait",
                      "description":"等待3000毫秒",
                      "waitTime":3000},
{
                      "action":"setPanelState",
                      "description":"设置 topcampaints to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                      "panelsToStates":[{
                          "panelPath":["7d58fb5471004ea0a939ec243cf3d533"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "repeat":3000,
                            "options":{
                              "animateOut":{
                                "easing":"slideLeft",
                                "duration":500},
                              "animateIn":{
                                "easing":"slideLeft",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"1c965183fe2d46418c0aae86632b0112",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"516fee01fd424787b6eeb2ee6648e06d",
                  "label":"",
                  "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9fc07c8b6344ed68544e3534c2e7cdf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/lefinshare/u45.png"}}]},
{
              "id":"d7e28ce322ce499ba43c85d849526d2f",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1e1925351620454ba798faf0f353da07",
                  "label":"",
                  "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a334d1f5617454581cafa07f345aefa",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/lefinshare/u47.png"}}]},
{
              "id":"536d400d4be1441e8baff012be40ab5a",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"822116523cf94fb4b904d83c3a033354",
                  "label":"",
                  "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8252bea89e64425ca6b1edea400f6d5c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/lefinshare/u49.png"}}]},
{
              "id":"dc9e109b079247bba9940ba16e79048f",
              "label":"状态4",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"34d808025a644b0abef8ba24a1c9fcc8",
                  "label":"",
                  "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":375,
                      "height":100}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"41aa6d07679e439a8b2353a51bb9eac3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d58fb5471004ea0a939ec243cf3d533",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":375,
                          "height":100}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/lefinshare/u51.png"}}]}]},
{
          "id":"5a2eacc20cd841c78a0de47a9bb8c797",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":330,
              "height":55},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"685dcfb04c5147f2b7893a0477e313b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":330,
                  "height":55},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 GSFstellar",
                      "target":{
                        "targetType":"page",
                        "url":"gsfstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/oldhome/u35.png"}},
{
          "id":"e814f4ec138b41af88300b0492af05c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":260},
            "size":{
              "width":262,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d8bd6f23a0a4c438b3a0aa77e8815d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":260},
                "size":{
                  "width":262,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBDstellar",
                      "target":{
                        "targetType":"page",
                        "url":"cbdstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u59.png"}},
{
          "id":"b7fbfa852ee14d4081028ded997b5a17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":48,
              "y":324},
            "size":{
              "width":282,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c242ee694e6d4c2ea57ba5ce059ffbf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":48,
                  "y":324},
                "size":{
                  "width":282,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBRstellar",
                      "target":{
                        "targetType":"page",
                        "url":"cbrstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u61.png"}},
{
          "id":"ecb99beee0f94553b9fd12a079857c43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":788,
              "y":313},
            "size":{
              "width":315,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2eaec2b3b764f07a8f4a4428467d746",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":788,
                  "y":313},
                "size":{
                  "width":315,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CCFstallar",
                      "target":{
                        "targetType":"page",
                        "url":"ccfstallar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u63.png"}},
{
          "id":"204998d7e1c140d38ccebe9ad1f64def",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":82,
              "y":366},
            "size":{
              "width":248,
              "height":28},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3abce6c22fb45c0b7f077b9c08d0980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":82,
                  "y":366},
                "size":{
                  "width":248,
                  "height":28},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 SmallBankForum",
                      "target":{
                        "targetType":"page",
                        "url":"smallbankforum.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u67.png"}},
{
          "id":"638154c88f6d4bcf82494ede5f8d7eef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":438,
              "y":365},
            "size":{
              "width":232,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b71d894d2a34c34badc78fa363cb8e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":438,
                  "y":365},
                "size":{
                  "width":232,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 LeFinShare",
                      "target":{
                        "targetType":"page",
                        "url":"lefinshare.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/gsfstellar/u32.png"}},
{
          "id":"ac9385c2f46a4686a1efa587974b78b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":788,
              "y":275},
            "size":{
              "width":294,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51768da141574b91b8517ab4f31ba477",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":788,
                  "y":275},
                "size":{
                  "width":294,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 ABSstellar",
                      "target":{
                        "targetType":"page",
                        "url":"absstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u65.png"}},
{
          "id":"a068e522e5dd4dd7bc15b7dd1f2ebaeb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1020,
              "y":167},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66be151776a6419eaa646d839f271529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":167},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90912a7f330b4ef08a9ad13aa20daaa8",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":940},
            "size":{
              "width":1110,
              "height":850}},
          "adaptiveStyles":{
}},
{
          "id":"edd8d2a5745146a9abd9ed774caddce9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":106}},
          "adaptiveStyles":{
},
          "masterId":"4717aadb7a9c492ea52bae53c0fe7f92"}]}},
  "masters":{
    "4717aadb7a9c492ea52bae53c0fe7f92":{
      "packageId":"4717aadb7a9c492ea52bae53c0fe7f92",
      "type":"Axure:Master",
      "name":"基础应用",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"09e8fc79a5f14c7a99eb5892e1876c40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":366,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef32ff36f7a6431984dab72d0b1576e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":366,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://123.59.176.75",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://123.59.176.75",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"c53c95e85a454f048228bf7bb8661d99",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":110,
                "y":0},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fa94b9cb02a4a809badae9c5c8744de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":110,
                    "y":0},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"d160475039954513a8916264a62070ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":452,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94a75bef1a5545d785df4e03174d03d7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":452,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"92f1433b0dce44b38b3ba68d6bf7fcca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":537,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"114dee27480144969dd47c62a6c93e6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":537,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000/common/projectList.html",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000/common/projectList.html",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"8ca5acff3129403e8d36c77c48bc40a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":622,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c6845ac8d8045259cca7868db810013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":622,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"aee4d0c2646644319c435099ef39eec6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":710,
                "y":0},
              "size":{
                "width":148,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c252398d5e2a428ba18295db3e6e5f8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":710,
                    "y":0},
                  "size":{
                    "width":148,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u15.png",
              "selected~":"images/lefinshare/u15_selected.png",
              "mouseOver~":"images/lefinshare/u15_mouseOver.png",
              "mouseDown~":"images/lefinshare/u15_mouseOver.png",
              "disabled~":"images/lefinshare/u15_mouseOver.png"}},
{
            "id":"e8f421743a96491892851fd3ae2a40c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"323b12dd97194b68ba857706d3216507",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"51b350f40bd343f18728a45ec923e313",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":220,
                "y":0},
              "size":{
                "width":136,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e1f4cef9f2e49188ff642467e9cca34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":220,
                    "y":0},
                  "size":{
                    "width":136,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u19.png",
              "selected~":"images/lefinshare/u19_selected.png",
              "mouseOver~":"images/lefinshare/u19_mouseOver.png",
              "mouseDown~":"images/lefinshare/u19_mouseOver.png",
              "disabled~":"images/lefinshare/u19_mouseOver.png"}},
{
            "id":"a398525097514925bf1e3364afa2f1a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":868,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2474207010164e20978b0c450cc48635",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":868,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}},
{
            "id":"afba7c40d3b945129b691a8802891f5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":988,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5dbc3d6059f4b039664550bfd50a180",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":988,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}}]}}},
  "objectPaths":{
    "44c00c895dd54c3882145e13f8a97937":{
      "scriptId":"u0"},
    "00d913d3a6fd43b49dbab0b9b6361f8f":{
      "scriptId":"u1"},
    "e90307c439d84103a6052cf76135310e":{
      "scriptId":"u2"},
    "49416dc552344a61a5650f196ebcefad":{
      "scriptId":"u3"},
    "bef698bfd60d40bba1d835f75f482b3d":{
      "scriptId":"u4"},
    "135e51e49f5d44e6aba724490fc74b01":{
      "scriptId":"u5"},
    "7918b95f50154205944e992756969934":{
      "scriptId":"u6"},
    "eecdff85f4db4be69c7d5228e2452311":{
      "scriptId":"u7"},
    "4da55bf2fdba4795abf57ccf3b3b0c6a":{
      "scriptId":"u8"},
    "ef109a31bf3d41daa2213fe9a9dfd61c":{
      "scriptId":"u9"},
    "03e4bbffecc7410ba675f34f99b13b5f":{
      "scriptId":"u10"},
    "16208100b0d44b1eb7735e1781ba1b43":{
      "scriptId":"u11"},
    "eb6c598b415540acbc4a23985f67735f":{
      "scriptId":"u12"},
    "b1d7acd4c1dd423593019052c6845161":{
      "scriptId":"u13"},
    "a4845d550dac4f66bce1a8d536668ae4":{
      "scriptId":"u14"},
    "33429bd6429d4007b6b97469f09a3079":{
      "scriptId":"u15"},
    "23704915e3b44135b0a5c253cfd80b89":{
      "scriptId":"u16"},
    "d83de9b0495c4624864584cf7760421d":{
      "scriptId":"u17"},
    "c91ce1aaf1114a16ae2c30121223dfa1":{
      "scriptId":"u18"},
    "c5605babd159432785490eca8d7211dd":{
      "scriptId":"u19"},
    "b7381274234c49a9ad1a220106791752":{
      "scriptId":"u20"},
    "60469e2ff18e42b19fce324843fe6052":{
      "scriptId":"u21"},
    "0c2084d40d7d4344acad2a1dc0c1f8e9":{
      "scriptId":"u22"},
    "265d038c5d5541178998cb19409d8a7c":{
      "scriptId":"u23"},
    "06f5f1515a824bff96584264a321ce94":{
      "scriptId":"u24"},
    "9249b59589b9419f95dae4042c559c3c":{
      "scriptId":"u25"},
    "7d58fb5471004ea0a939ec243cf3d533":{
      "scriptId":"u26"},
    "516fee01fd424787b6eeb2ee6648e06d":{
      "scriptId":"u27"},
    "e9fc07c8b6344ed68544e3534c2e7cdf":{
      "scriptId":"u28"},
    "1e1925351620454ba798faf0f353da07":{
      "scriptId":"u29"},
    "7a334d1f5617454581cafa07f345aefa":{
      "scriptId":"u30"},
    "822116523cf94fb4b904d83c3a033354":{
      "scriptId":"u31"},
    "8252bea89e64425ca6b1edea400f6d5c":{
      "scriptId":"u32"},
    "34d808025a644b0abef8ba24a1c9fcc8":{
      "scriptId":"u33"},
    "41aa6d07679e439a8b2353a51bb9eac3":{
      "scriptId":"u34"},
    "5a2eacc20cd841c78a0de47a9bb8c797":{
      "scriptId":"u35"},
    "685dcfb04c5147f2b7893a0477e313b2":{
      "scriptId":"u36"},
    "e814f4ec138b41af88300b0492af05c2":{
      "scriptId":"u37"},
    "9d8bd6f23a0a4c438b3a0aa77e8815d7":{
      "scriptId":"u38"},
    "b7fbfa852ee14d4081028ded997b5a17":{
      "scriptId":"u39"},
    "c242ee694e6d4c2ea57ba5ce059ffbf9":{
      "scriptId":"u40"},
    "ecb99beee0f94553b9fd12a079857c43":{
      "scriptId":"u41"},
    "d2eaec2b3b764f07a8f4a4428467d746":{
      "scriptId":"u42"},
    "204998d7e1c140d38ccebe9ad1f64def":{
      "scriptId":"u43"},
    "b3abce6c22fb45c0b7f077b9c08d0980":{
      "scriptId":"u44"},
    "638154c88f6d4bcf82494ede5f8d7eef":{
      "scriptId":"u45"},
    "3b71d894d2a34c34badc78fa363cb8e4":{
      "scriptId":"u46"},
    "ac9385c2f46a4686a1efa587974b78b9":{
      "scriptId":"u47"},
    "51768da141574b91b8517ab4f31ba477":{
      "scriptId":"u48"},
    "a068e522e5dd4dd7bc15b7dd1f2ebaeb":{
      "scriptId":"u49"},
    "66be151776a6419eaa646d839f271529":{
      "scriptId":"u50"},
    "90912a7f330b4ef08a9ad13aa20daaa8":{
      "scriptId":"u51"},
    "edd8d2a5745146a9abd9ed774caddce9":{
      "scriptId":"u52",
      "09e8fc79a5f14c7a99eb5892e1876c40":{
        "scriptId":"u53"},
      "ef32ff36f7a6431984dab72d0b1576e7":{
        "scriptId":"u54"},
      "c53c95e85a454f048228bf7bb8661d99":{
        "scriptId":"u55"},
      "5fa94b9cb02a4a809badae9c5c8744de":{
        "scriptId":"u56"},
      "d160475039954513a8916264a62070ce":{
        "scriptId":"u57"},
      "94a75bef1a5545d785df4e03174d03d7":{
        "scriptId":"u58"},
      "92f1433b0dce44b38b3ba68d6bf7fcca":{
        "scriptId":"u59"},
      "114dee27480144969dd47c62a6c93e6e":{
        "scriptId":"u60"},
      "8ca5acff3129403e8d36c77c48bc40a5":{
        "scriptId":"u61"},
      "4c6845ac8d8045259cca7868db810013":{
        "scriptId":"u62"},
      "aee4d0c2646644319c435099ef39eec6":{
        "scriptId":"u63"},
      "c252398d5e2a428ba18295db3e6e5f8e":{
        "scriptId":"u64"},
      "e8f421743a96491892851fd3ae2a40c3":{
        "scriptId":"u65"},
      "323b12dd97194b68ba857706d3216507":{
        "scriptId":"u66"},
      "51b350f40bd343f18728a45ec923e313":{
        "scriptId":"u67"},
      "2e1f4cef9f2e49188ff642467e9cca34":{
        "scriptId":"u68"},
      "a398525097514925bf1e3364afa2f1a4":{
        "scriptId":"u69"},
      "2474207010164e20978b0c450cc48635":{
        "scriptId":"u70"},
      "afba7c40d3b945129b691a8802891f5c":{
        "scriptId":"u71"},
      "d5dbc3d6059f4b039664550bfd50a180":{
        "scriptId":"u72"}}}});