$axure.loadCurrentPage({
  "url":"cbra__.html",
  "generationDate":new Date(1482494479567.8),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6905674a90dc4a53821f46ef68646135",
    "type":"Axure:Page",
    "name":"CBRA简介",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d40cf393a136436288b404ca70a892c6",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":0},
            "size":{
              "width":580,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65f7ef6851e744899d874596c16b2ec9",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":580,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b5db8cc2996466aafbe96b285225e34",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6281e6e4dd77461dbac3147a8fd085b4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 新窗口/标签页 打开 http://150.242.56.116",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"http://150.242.56.116",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"new"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"90a1d72005e34d69989b58c2033f9c37",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ba885c43e3a4ad8a91cfe51a4d3c46f",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9f05374f46a04996a85d70e4138de6da",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":340,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d12d1866db7345659c6b1daaf146299b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":340,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5d2efd4f54174172b9d118133d90b946",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e2ee3a4a8ca14134a56e78df6a36ad19",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":420,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fe3f6dcbc8734032911b880a83f39525",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3c50a907a0a44a609becb71b4c9e9f53",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"59b2b8889a60438b96700536d3e835bb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":180,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"58545f54c77d467f9298a8dcea5100a4",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":180,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"ae1f835499074e38bad3a7cb56c0bb0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":26,
              "y":136},
            "size":{
              "width":744,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9fb5b054dde431fb0eac5ca891bb36f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":26,
                  "y":136},
                "size":{
                  "width":744,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实验室",
                      "target":{
                        "targetType":"page",
                        "url":"实验室.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e47aeb98c19844b7b9cb1dcd5b35486f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":26,
              "y":167},
            "size":{
              "width":494,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c6b8af884d149c39568812c3fc118f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":26,
                  "y":167},
                "size":{
                  "width":494,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d9fb65bba4f14b6395f4a54b778e623a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1428},
            "size":{
              "width":1131,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35dbec0060a241d39c7d99ecbeda7b9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1428},
                "size":{
                  "width":1131,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u53.png"}},
{
          "id":"e0f44e03d54241c98e8d808f102ed404",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":716,
              "y":2061},
            "size":{
              "width":383,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fea336e61ea04e8bb305bbfe657e4ec8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":716,
                  "y":2061},
                "size":{
                  "width":383,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"300c3ba47308419ca76450024dd8177e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":18.5,
              "y":10},
            "size":{
              "width":335,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d639c941fd2450180385c8d13e58725",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":18.5,
                  "y":10},
                "size":{
                  "width":335,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBRA简介",
                      "target":{
                        "targetType":"page",
                        "url":"cbra__.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u61.png"}},
{
          "id":"222da663827c412e8409070dbad72527",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":30.5,
              "y":1959},
            "size":{
              "width":330,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51099718ad8841588e7dfc297e02b99e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30.5,
                  "y":1959},
                "size":{
                  "width":330,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 GSFstellar",
                      "target":{
                        "targetType":"page",
                        "url":"gsfstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u57.png"}},
{
          "id":"93149c50e00d43f6881d0c18b6ac5d86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":434.5,
              "y":1947},
            "size":{
              "width":262,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a5a9d5ad5d64fe686e4b37730cba131",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":434.5,
                  "y":1947},
                "size":{
                  "width":262,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBDstellar",
                      "target":{
                        "targetType":"page",
                        "url":"cbdstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u59.png"}},
{
          "id":"9006318849ae4199a5626e2c392b7225",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":767.5,
              "y":1990},
            "size":{
              "width":315,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c5df22695f49cb9dacbb281f45683e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":767.5,
                  "y":1990},
                "size":{
                  "width":315,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CCFstallar",
                      "target":{
                        "targetType":"page",
                        "url":"ccfstallar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u63.png"}},
{
          "id":"b5bf5d7a80be454aad5b2a7cc0a09021",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":102.5,
              "y":2067},
            "size":{
              "width":248,
              "height":28},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26761861c1a64f86ab8213e8f483922e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":102.5,
                  "y":2067},
                "size":{
                  "width":248,
                  "height":28},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 SmallBankForum",
                      "target":{
                        "targetType":"page",
                        "url":"smallbankforum.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u67.png"}},
{
          "id":"28c7154dccfd4eaa970906d07c801a1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":455.5,
              "y":2067},
            "size":{
              "width":232,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5aa96254317404fa5eed06aa99260d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":455.5,
                  "y":2067},
                "size":{
                  "width":232,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 LeFinShare",
                      "target":{
                        "targetType":"page",
                        "url":"lefinshare.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/gsfstellar/u32.png"}},
{
          "id":"84c7cc39d2be4efa8ca625de66fa9046",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":45.5,
              "y":2019},
            "size":{
              "width":305,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f99c6d7372304e388d568222fb6c92a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":45.5,
                  "y":2019},
                "size":{
                  "width":305,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 ABSstellar",
                      "target":{
                        "targetType":"page",
                        "url":"absstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u65.png"}},
{
          "id":"d0d37e1febef48dfa9ac65d5c44e688b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1020,
              "y":167},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f507ee011aa460c8bdf82f5de997438",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1020,
                  "y":167},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b55eb4a2f13747b0890ee7bc2bb57000",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":1900},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1d05a14f6f54c5ba150c119d4b344e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":1900},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d63ce8a3f0c438a9bc471208e357800",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":366},
            "size":{
              "width":1110,
              "height":850}},
          "adaptiveStyles":{
}},
{
          "id":"0e4ac0ec94f9457c9c28cfb77d7b619e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"4717aadb7a9c492ea52bae53c0fe7f92"},
{
          "id":"75fdabfac86f45249afa344c0ded6a8e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":196}},
          "adaptiveStyles":{
},
          "masterId":"0ad5b74807be43b7a053e1730e651192"},
{
          "id":"b04089db3f3744e28d69509dcf01ed21",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":196}},
          "adaptiveStyles":{
},
          "masterId":"61fbdc6491d648b498cdae46617e334d"},
{
          "id":"a3138d5b5c14461ebea9579226bb967d",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1218},
            "size":{
              "width":1110,
              "height":200}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "4717aadb7a9c492ea52bae53c0fe7f92":{
      "packageId":"4717aadb7a9c492ea52bae53c0fe7f92",
      "type":"Axure:Master",
      "name":"基础应用",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"09e8fc79a5f14c7a99eb5892e1876c40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":366,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef32ff36f7a6431984dab72d0b1576e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":366,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://123.59.176.75",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://123.59.176.75",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"c53c95e85a454f048228bf7bb8661d99",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":110,
                "y":0},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fa94b9cb02a4a809badae9c5c8744de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":110,
                    "y":0},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"d160475039954513a8916264a62070ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":452,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94a75bef1a5545d785df4e03174d03d7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":452,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"92f1433b0dce44b38b3ba68d6bf7fcca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":537,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"114dee27480144969dd47c62a6c93e6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":537,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000/common/projectList.html",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000/common/projectList.html",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"8ca5acff3129403e8d36c77c48bc40a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":622,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c6845ac8d8045259cca7868db810013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":622,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"aee4d0c2646644319c435099ef39eec6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":710,
                "y":0},
              "size":{
                "width":148,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c252398d5e2a428ba18295db3e6e5f8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":710,
                    "y":0},
                  "size":{
                    "width":148,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u15.png",
              "selected~":"images/lefinshare/u15_selected.png",
              "mouseOver~":"images/lefinshare/u15_mouseOver.png",
              "mouseDown~":"images/lefinshare/u15_mouseOver.png",
              "disabled~":"images/lefinshare/u15_mouseOver.png"}},
{
            "id":"e8f421743a96491892851fd3ae2a40c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"323b12dd97194b68ba857706d3216507",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"51b350f40bd343f18728a45ec923e313",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":220,
                "y":0},
              "size":{
                "width":136,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e1f4cef9f2e49188ff642467e9cca34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":220,
                    "y":0},
                  "size":{
                    "width":136,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u19.png",
              "selected~":"images/lefinshare/u19_selected.png",
              "mouseOver~":"images/lefinshare/u19_mouseOver.png",
              "mouseDown~":"images/lefinshare/u19_mouseOver.png",
              "disabled~":"images/lefinshare/u19_mouseOver.png"}},
{
            "id":"a398525097514925bf1e3364afa2f1a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":868,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2474207010164e20978b0c450cc48635",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":868,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}},
{
            "id":"afba7c40d3b945129b691a8802891f5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":988,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5dbc3d6059f4b039664550bfd50a180",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":988,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}}]}},
    "0ad5b74807be43b7a053e1730e651192":{
      "packageId":"0ad5b74807be43b7a053e1730e651192",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
            "label":"topcampaints",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":681,
                "height":160}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"wait",
                        "description":"等待3000毫秒",
                        "waitTime":3000},
{
                        "action":"setPanelState",
                        "description":"设置 topcampaints to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                        "panelsToStates":[{
                            "panelPath":["ab8b93c14d654a7fac3f2a18cf8c3cc2"],
                            "stateInfo":{
                              "setStateType":"next",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":true,
                              "showWhenSet":false,
                              "repeat":3000,
                              "options":{
                                "animateOut":{
                                  "easing":"slideLeft",
                                  "duration":500},
                                "animateIn":{
                                  "easing":"slideLeft",
                                  "duration":500},
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"71f05a5938e04a09ac34b52219217f38",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"ac30936e697b4ccba0c69fd012c60ba7",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"278b2c708e9f4223b8c22c96de6bdd0e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u45.png"}}]},
{
                "id":"b25f687248484d08a44a52ea76e6efb2",
                "label":"状态2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b11604d5c8434d7d91c65d3980187c9f",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62e4ab509f9842798658f3c6422c6d8a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u47.png"}}]},
{
                "id":"f21b66a172e84cedac7791bdc2d3848e",
                "label":"状态3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"19bf8be82cbf42d3b172703b7a7a1fb3",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8312d21c7eca4d9a955db2547f158789",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u49.png"}}]},
{
                "id":"c266683103084d3f920197991f8a267a",
                "label":"状态4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4f5b9963e8dc44ed8f110df6d9f8af32",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8c2674e6d00d4aa59cb7389b08d224b0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u51.png"}}]}]}]}},
    "61fbdc6491d648b498cdae46617e334d":{
      "packageId":"61fbdc6491d648b498cdae46617e334d",
      "type":"Axure:Master",
      "name":"更多消息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa9c65ad014547878c7231230a6484ea",
            "label":"topcampaints",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":419,
                "height":160}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"wait",
                        "description":"等待5000毫秒",
                        "waitTime":5000},
{
                        "action":"setPanelState",
                        "description":"设置 topcampaints to 下一步 淡入淡出 out 500ms 淡入淡出 in 500ms wrap repeat every 5000 ms",
                        "panelsToStates":[{
                            "panelPath":["aa9c65ad014547878c7231230a6484ea"],
                            "stateInfo":{
                              "setStateType":"next",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":true,
                              "showWhenSet":false,
                              "repeat":5000,
                              "options":{
                                "animateOut":{
                                  "easing":"fade",
                                  "duration":500},
                                "animateIn":{
                                  "easing":"fade",
                                  "duration":500},
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3ae82fa30cda41cca54dc3f0d646d3de",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b01681d73c98441199246a6e37b2357a",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":420,
                        "height":161}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4646f876e79a4c9d9e1c50709d289663",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":420,
                            "height":161}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://150.242.56.112:9003",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://150.242.56.112:9003",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/lefinshare/u75.png"}}]},
{
                "id":"069e5e85cdf64dae9479dd4cdfafdfb3",
                "label":"状态2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"537f19aa81074d6cab8ae3ff144f7113",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":420,
                        "height":164},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"370655ada466455f85647fcc33bd3a11",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":420,
                            "height":164},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u77.png"}},
{
                    "id":"f9f60104680a4f709579a854d7be7d4c",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":55,
                        "y":68},
                      "size":{
                        "width":310,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"37327b097ed446caa541b0e228ce73d4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":55,
                            "y":68},
                          "size":{
                            "width":310,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]},
{
                "id":"993dfe2b8ad74e19a65dfbc860281737",
                "label":"状态3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"0a87521ea4a54eaa965ed88bba3054a5",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-230,
                        "y":-17},
                      "size":{
                        "width":680,
                        "height":190}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"691328232e4745be87abf2e8f390c830",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-230,
                            "y":-17},
                          "size":{
                            "width":680,
                            "height":190}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u49.png"}}]},
{
                "id":"f7153b7ed1734082874e567967e67d20",
                "label":"状态4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"924ca9899a1c4018a7339f8c418ecd0f",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-170,
                        "y":-3},
                      "size":{
                        "width":680,
                        "height":164}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2c264cb4e947fabb497d345d7ae522",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-170,
                            "y":-3},
                          "size":{
                            "width":680,
                            "height":164}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u51.png"}}]},
{
                "id":"3b96a2edd77e4e918d2a4495f6c70dbd",
                "label":"状态5",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"fad3e47fa11b4b2f9ed93683dcd4c4fb",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-40,
                        "y":0},
                      "size":{
                        "width":470,
                        "height":164},
                      "cornerRadiusTopLeft":"2"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0764d68807a44b0783290af1d38daac4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-40,
                            "y":0},
                          "size":{
                            "width":470,
                            "height":164},
                          "cornerRadiusTopLeft":"2"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://www.meimuzc.com",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://www.meimuzc.com",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/lefinshare/u85.png"}}]}]}]}}},
  "objectPaths":{
    "d40cf393a136436288b404ca70a892c6":{
      "scriptId":"u0"},
    "65f7ef6851e744899d874596c16b2ec9":{
      "scriptId":"u1"},
    "8b5db8cc2996466aafbe96b285225e34":{
      "scriptId":"u2"},
    "6281e6e4dd77461dbac3147a8fd085b4":{
      "scriptId":"u3"},
    "59b2b8889a60438b96700536d3e835bb":{
      "scriptId":"u4"},
    "58545f54c77d467f9298a8dcea5100a4":{
      "scriptId":"u5"},
    "90a1d72005e34d69989b58c2033f9c37":{
      "scriptId":"u6"},
    "8ba885c43e3a4ad8a91cfe51a4d3c46f":{
      "scriptId":"u7"},
    "9f05374f46a04996a85d70e4138de6da":{
      "scriptId":"u8"},
    "d12d1866db7345659c6b1daaf146299b":{
      "scriptId":"u9"},
    "5d2efd4f54174172b9d118133d90b946":{
      "scriptId":"u10"},
    "e2ee3a4a8ca14134a56e78df6a36ad19":{
      "scriptId":"u11"},
    "fe3f6dcbc8734032911b880a83f39525":{
      "scriptId":"u12"},
    "3c50a907a0a44a609becb71b4c9e9f53":{
      "scriptId":"u13"},
    "ae1f835499074e38bad3a7cb56c0bb0f":{
      "scriptId":"u14"},
    "f9fb5b054dde431fb0eac5ca891bb36f":{
      "scriptId":"u15"},
    "e47aeb98c19844b7b9cb1dcd5b35486f":{
      "scriptId":"u16"},
    "2c6b8af884d149c39568812c3fc118f3":{
      "scriptId":"u17"},
    "d9fb65bba4f14b6395f4a54b778e623a":{
      "scriptId":"u18"},
    "35dbec0060a241d39c7d99ecbeda7b9c":{
      "scriptId":"u19"},
    "e0f44e03d54241c98e8d808f102ed404":{
      "scriptId":"u20"},
    "fea336e61ea04e8bb305bbfe657e4ec8":{
      "scriptId":"u21"},
    "300c3ba47308419ca76450024dd8177e":{
      "scriptId":"u22"},
    "2d639c941fd2450180385c8d13e58725":{
      "scriptId":"u23"},
    "222da663827c412e8409070dbad72527":{
      "scriptId":"u24"},
    "51099718ad8841588e7dfc297e02b99e":{
      "scriptId":"u25"},
    "93149c50e00d43f6881d0c18b6ac5d86":{
      "scriptId":"u26"},
    "5a5a9d5ad5d64fe686e4b37730cba131":{
      "scriptId":"u27"},
    "9006318849ae4199a5626e2c392b7225":{
      "scriptId":"u28"},
    "54c5df22695f49cb9dacbb281f45683e":{
      "scriptId":"u29"},
    "b5bf5d7a80be454aad5b2a7cc0a09021":{
      "scriptId":"u30"},
    "26761861c1a64f86ab8213e8f483922e":{
      "scriptId":"u31"},
    "28c7154dccfd4eaa970906d07c801a1c":{
      "scriptId":"u32"},
    "a5aa96254317404fa5eed06aa99260d3":{
      "scriptId":"u33"},
    "84c7cc39d2be4efa8ca625de66fa9046":{
      "scriptId":"u34"},
    "f99c6d7372304e388d568222fb6c92a1":{
      "scriptId":"u35"},
    "d0d37e1febef48dfa9ac65d5c44e688b":{
      "scriptId":"u36"},
    "5f507ee011aa460c8bdf82f5de997438":{
      "scriptId":"u37"},
    "b55eb4a2f13747b0890ee7bc2bb57000":{
      "scriptId":"u38"},
    "c1d05a14f6f54c5ba150c119d4b344e5":{
      "scriptId":"u39"},
    "8d63ce8a3f0c438a9bc471208e357800":{
      "scriptId":"u40"},
    "0e4ac0ec94f9457c9c28cfb77d7b619e":{
      "scriptId":"u41",
      "09e8fc79a5f14c7a99eb5892e1876c40":{
        "scriptId":"u42"},
      "ef32ff36f7a6431984dab72d0b1576e7":{
        "scriptId":"u43"},
      "c53c95e85a454f048228bf7bb8661d99":{
        "scriptId":"u44"},
      "5fa94b9cb02a4a809badae9c5c8744de":{
        "scriptId":"u45"},
      "d160475039954513a8916264a62070ce":{
        "scriptId":"u46"},
      "94a75bef1a5545d785df4e03174d03d7":{
        "scriptId":"u47"},
      "92f1433b0dce44b38b3ba68d6bf7fcca":{
        "scriptId":"u48"},
      "114dee27480144969dd47c62a6c93e6e":{
        "scriptId":"u49"},
      "8ca5acff3129403e8d36c77c48bc40a5":{
        "scriptId":"u50"},
      "4c6845ac8d8045259cca7868db810013":{
        "scriptId":"u51"},
      "aee4d0c2646644319c435099ef39eec6":{
        "scriptId":"u52"},
      "c252398d5e2a428ba18295db3e6e5f8e":{
        "scriptId":"u53"},
      "e8f421743a96491892851fd3ae2a40c3":{
        "scriptId":"u54"},
      "323b12dd97194b68ba857706d3216507":{
        "scriptId":"u55"},
      "51b350f40bd343f18728a45ec923e313":{
        "scriptId":"u56"},
      "2e1f4cef9f2e49188ff642467e9cca34":{
        "scriptId":"u57"},
      "a398525097514925bf1e3364afa2f1a4":{
        "scriptId":"u58"},
      "2474207010164e20978b0c450cc48635":{
        "scriptId":"u59"},
      "afba7c40d3b945129b691a8802891f5c":{
        "scriptId":"u60"},
      "d5dbc3d6059f4b039664550bfd50a180":{
        "scriptId":"u61"}},
    "75fdabfac86f45249afa344c0ded6a8e":{
      "scriptId":"u62",
      "ab8b93c14d654a7fac3f2a18cf8c3cc2":{
        "scriptId":"u63"},
      "ac30936e697b4ccba0c69fd012c60ba7":{
        "scriptId":"u64"},
      "278b2c708e9f4223b8c22c96de6bdd0e":{
        "scriptId":"u65"},
      "b11604d5c8434d7d91c65d3980187c9f":{
        "scriptId":"u66"},
      "62e4ab509f9842798658f3c6422c6d8a":{
        "scriptId":"u67"},
      "19bf8be82cbf42d3b172703b7a7a1fb3":{
        "scriptId":"u68"},
      "8312d21c7eca4d9a955db2547f158789":{
        "scriptId":"u69"},
      "4f5b9963e8dc44ed8f110df6d9f8af32":{
        "scriptId":"u70"},
      "8c2674e6d00d4aa59cb7389b08d224b0":{
        "scriptId":"u71"}},
    "b04089db3f3744e28d69509dcf01ed21":{
      "scriptId":"u72",
      "aa9c65ad014547878c7231230a6484ea":{
        "scriptId":"u73"},
      "b01681d73c98441199246a6e37b2357a":{
        "scriptId":"u74"},
      "4646f876e79a4c9d9e1c50709d289663":{
        "scriptId":"u75"},
      "537f19aa81074d6cab8ae3ff144f7113":{
        "scriptId":"u76"},
      "370655ada466455f85647fcc33bd3a11":{
        "scriptId":"u77"},
      "f9f60104680a4f709579a854d7be7d4c":{
        "scriptId":"u78"},
      "37327b097ed446caa541b0e228ce73d4":{
        "scriptId":"u79"},
      "0a87521ea4a54eaa965ed88bba3054a5":{
        "scriptId":"u80"},
      "691328232e4745be87abf2e8f390c830":{
        "scriptId":"u81"},
      "924ca9899a1c4018a7339f8c418ecd0f":{
        "scriptId":"u82"},
      "6f2c264cb4e947fabb497d345d7ae522":{
        "scriptId":"u83"},
      "fad3e47fa11b4b2f9ed93683dcd4c4fb":{
        "scriptId":"u84"},
      "0764d68807a44b0783290af1d38daac4":{
        "scriptId":"u85"}},
    "a3138d5b5c14461ebea9579226bb967d":{
      "scriptId":"u86"}}});