$axure.loadCurrentPage({
  "url":"资产信任.html",
  "generationDate":new Date(1482495099633.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f45bf4cf4a94b9aa86be6f1bbdd00ee",
    "type":"Axure:Page",
    "name":"资产信任",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3164b354f77c4a0dae910eb65b03a740",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "size":{
              "width":670,
              "height":976}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da30bb69f91b4eb29dda059c7d83fbf9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":670,
                  "height":976}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "3164b354f77c4a0dae910eb65b03a740":{
      "scriptId":"u0"},
    "da30bb69f91b4eb29dda059c7d83fbf9":{
      "scriptId":"u1"}}});