$axure.loadCurrentPage({
  "url":"查询查复.html",
  "generationDate":new Date(1482495099590.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cc89a30841a64502ad2bba5384b3aa8b",
    "type":"Axure:Page",
    "name":"查询查复",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc0f4847d20541ee8a12368c32e7b998",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":7,
              "y":3},
            "size":{
              "width":185,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ed5500a816c4646bd9e49988b37352e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":7,
                  "y":3},
                "size":{
                  "width":185,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc0f4847d20541ee8a12368c32e7b998":{
      "scriptId":"u0"},
    "7ed5500a816c4646bd9e49988b37352e":{
      "scriptId":"u1"}}});