$axure.loadCurrentPage({
  "url":"实验室.html",
  "generationDate":new Date(1482495098810.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"56682ba1238b47deba33c966b9e729e7",
    "type":"Axure:Page",
    "name":"实验室",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 被选中的 A1 = &quot;true&quot;, 与<br> 被选中的 B1 = &quot;true&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["a4ed4fae471d45c1895292f8ecd09855"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]},
{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["021f3058b8684582988278a9eae27dc1"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"1331e05edd57423aacb06fa062870c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":0,
              "y":69},
            "size":{
              "width":1184,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"848383545f2b4230b3f8e48a9e0fe0b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":0,
                  "y":69},
                "size":{
                  "width":1184,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u0.png"}},
{
          "id":"85ff4e385ecc42558fe6408c177f6fc1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-138,
              "y":745},
            "size":{
              "width":1082,
              "height":9},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df3c8c598251456394ec4f7bef94a372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-138,
                  "y":745},
                "size":{
                  "width":1082,
                  "height":9},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u2.png"}},
{
          "id":"d6c307e675c041698920a8b6bf063366",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2713,
              "y":745},
            "size":{
              "width":657,
              "height":9},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9afea426e3d740cab1e8995bda2466c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2713,
                  "y":745},
                "size":{
                  "width":657,
                  "height":9},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u4.png"}},
{
          "id":"7c63c67fb5f847e6a758f03bd52b95b3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2713,
              "y":754},
            "size":{
              "width":657,
              "height":2065},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50772e8061e646b1bd54fe22b69b7a34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2713,
                  "y":754},
                "size":{
                  "width":657,
                  "height":2065},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u6.png"}},
{
          "id":"eb973ba00be44e62b0564f3bca1ebe3f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":944,
              "y":745},
            "size":{
              "width":1769,
              "height":9},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3971e4da28041b787b7f9e705f7950e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":944,
                  "y":745},
                "size":{
                  "width":1769,
                  "height":9},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u8.png"}},
{
          "id":"5bbf95933243438d8cfe4a2d88430d80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2713,
              "y":339},
            "size":{
              "width":657,
              "height":406},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca2a83185c2b4e1b89b3cf7aa8a2e10e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2713,
                  "y":339},
                "size":{
                  "width":657,
                  "height":406},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/实验室/u10.png"}},
{
          "id":"0481ac1bbc954308ad6e692000d9a396",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "verticalAlignment":"bottom",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":213,
              "y":10},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c4e230194db4b88959abcb3b4d67bb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "verticalAlignment":"bottom",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":213,
                  "y":10},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 OLDHome",
                      "target":{
                        "targetType":"page",
                        "url":"oldhome.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8916d871c0824deeab955df73380e321",
          "label":"A2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF}}},
            "location":{
              "x":830,
              "y":10},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16ef9ea4e7eb4e3d8e2079cab31b46ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399FF}}},
                "location":{
                  "x":830,
                  "y":10},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 A2 = &quot;true&quot;, 与<br> 被选中的 A3 = &quot;false&quot;, 与<br> 被选中的 A1 = &quot;false&quot;, 与<br> 被选中的 A4 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8916d871c0824deeab955df73380e321"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b481d7fad16a4cd4ac6de59777bf6bea"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a4ed4fae471d45c1895292f8ecd09855"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f52ffa4debd746bf8856c871a83d748c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/a2_u14.png",
            "selected~":"images/实验室/a2_u14_selected.png",
            "mouseOver~":"images/实验室/a2_u14_mouseOver.png",
            "mouseDown~":"images/实验室/a2_u14_mouseOver.png"}},
{
          "id":"b481d7fad16a4cd4ac6de59777bf6bea",
          "label":"A3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF}}},
            "location":{
              "x":930,
              "y":10},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78bef4b7150e490da20b926a290d9a4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399FF}}},
                "location":{
                  "x":930,
                  "y":10},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 A2 = &quot;false&quot;, 与<br> 被选中的 A3 = &quot;true&quot;, 与<br> 被选中的 A1 = &quot;false&quot;, 与<br> 被选中的 A4 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8916d871c0824deeab955df73380e321"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b481d7fad16a4cd4ac6de59777bf6bea"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a4ed4fae471d45c1895292f8ecd09855"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f52ffa4debd746bf8856c871a83d748c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/a2_u14.png",
            "selected~":"images/实验室/a2_u14_selected.png",
            "mouseOver~":"images/实验室/a2_u14_mouseOver.png",
            "mouseDown~":"images/实验室/a2_u14_mouseOver.png"}},
{
          "id":"a4ed4fae471d45c1895292f8ecd09855",
          "label":"A1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":730,
              "y":10},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff30aef420f42c49526e391e03b3ecc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399FF}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":730,
                  "y":10},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 A2 = &quot;false&quot;, 与<br> 被选中的 A3 = &quot;false&quot;, 与<br> 被选中的 A1 = &quot;true&quot;, 与<br> 被选中的 A4 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8916d871c0824deeab955df73380e321"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b481d7fad16a4cd4ac6de59777bf6bea"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a4ed4fae471d45c1895292f8ecd09855"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f52ffa4debd746bf8856c871a83d748c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/a1_u18.png",
            "selected~":"images/实验室/a2_u14_selected.png",
            "mouseOver~":"images/实验室/a2_u14_mouseOver.png",
            "mouseDown~":"images/实验室/a2_u14_mouseOver.png"}},
{
          "id":"f52ffa4debd746bf8856c871a83d748c",
          "label":"A4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1}},
              "selected":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF}}},
            "location":{
              "x":1030,
              "y":10},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f7d2259ed204c31bc4cb37f7b879d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1}},
                  "selected":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399FF}}},
                "location":{
                  "x":1030,
                  "y":10},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 A2 = &quot;false&quot;, 与<br> 被选中的 A3 = &quot;false&quot;, 与<br> 被选中的 A1 = &quot;false&quot;, 与<br> 被选中的 A4 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8916d871c0824deeab955df73380e321"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["b481d7fad16a4cd4ac6de59777bf6bea"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a4ed4fae471d45c1895292f8ecd09855"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["f52ffa4debd746bf8856c871a83d748c"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/a2_u14.png",
            "selected~":"images/实验室/a2_u14_selected.png",
            "mouseOver~":"images/实验室/a2_u14_mouseOver.png",
            "mouseDown~":"images/实验室/a2_u14_mouseOver.png"}},
{
          "id":"9d57511ef0c74cbcb759fb32d7172f99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":912,
              "y":40},
            "size":{
              "width":218,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef82551787814c1a8552c0caf50c316b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":912,
                  "y":40},
                "size":{
                  "width":218,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"021f3058b8684582988278a9eae27dc1",
          "label":"B1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff93e77da0f4c8398c227b6e5061530",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;true&quot;, 与<br> 被选中的 B2 = &quot;false&quot;, 与<br> 被选中的 B3 = &quot;false&quot;, 与<br> 被选中的 B4 = &quot;false&quot;, 与<br> 被选中的 B5 = &quot;false&quot;, 与<br> 被选中的 B6 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 简介 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"简介.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"249aca9520dd4ae992408bc6fdbfb4ce",
          "label":"B2",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":188,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92c3c0bccc0f4382840e802c755f9d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":188,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;false&quot;, 与<br> 被选中的 B2 = &quot;true&quot;, 与<br> 被选中的 B3 = &quot;false&quot;, 与<br> 被选中的 B4 = &quot;false&quot;, 与<br> 被选中的 B5 = &quot;false&quot;, 与<br> 被选中的 B6 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 创建账户 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"创建账户.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"a3d848a68d144f4b9603c27c2beeb6d7",
          "label":"B3",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":333,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6d0fa7981204f6d8f0ee2455dc89ee4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":333,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;false&quot;, 与<br> 被选中的 B2 = &quot;false&quot;, 与<br> 被选中的 B3 = &quot;true&quot;, 与<br> 被选中的 B4 = &quot;false&quot;, 与<br> 被选中的 B5 = &quot;false&quot;, 与<br> 被选中的 B6 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 业务终端 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"业务终端.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"135d476e00ac45ccbf83ecdf7f7fe006",
          "label":"B4",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":480,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"449e442c0efd4f978ec2eb02d6964cbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":480,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;false&quot;, 与<br> 被选中的 B2 = &quot;false&quot;, 与<br> 被选中的 B3 = &quot;false&quot;, 与<br> 被选中的 B4 = &quot;true&quot;, 与<br> 被选中的 B5 = &quot;false&quot;, 与<br> 被选中的 B6 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 新增业务 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"新增业务.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"465f9bab4c924df986b9c99dffef276f",
          "label":"B5",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":625,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c7252b5801c4615b0f3a445c827547e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":625,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;false&quot;, 与<br> 被选中的 B2 = &quot;false&quot;, 与<br> 被选中的 B3 = &quot;false&quot;, 与<br> 被选中的 B4 = &quot;false&quot;, 与<br> 被选中的 B5 = &quot;true&quot;, 与<br> 被选中的 B6 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 业务签名 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"业务签名.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"8d5c840a2767487c94581f3946d6c08c",
          "label":"B6",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "stateStyles":{
              "mouseOver":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "selected":{
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "disabled":{
                "borderWidth":"-1",
                "linePattern":"none"}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":770,
              "y":94},
            "size":{
              "width":135,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8e51be3ebd7448e8748661d1ff533ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "stateStyles":{
                  "mouseOver":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "selected":{
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "disabled":{
                    "borderWidth":"-1",
                    "linePattern":"none"}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":770,
                  "y":94},
                "size":{
                  "width":135,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 被选中的 B1 = &quot;false&quot;, 与<br> 被选中的 B2 = &quot;false&quot;, 与<br> 被选中的 B3 = &quot;false&quot;, 与<br> 被选中的 B4 = &quot;false&quot;, 与<br> 被选中的 B5 = &quot;false&quot;, 与<br> 被选中的 B6 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["021f3058b8684582988278a9eae27dc1"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["249aca9520dd4ae992408bc6fdbfb4ce"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a3d848a68d144f4b9603c27c2beeb6d7"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["135d476e00ac45ccbf83ecdf7f7fe006"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["465f9bab4c924df986b9c99dffef276f"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["8d5c840a2767487c94581f3946d6c08c"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"linkFrame",
                      "description":"打开 查询查复 在 frm",
                      "linkType":"frame",
                      "framesToTargets":[{
                          "framePath":["9bdfeac0fcdf4a209119e54b728cf236"],
                          "target":{
                            "targetType":"page",
                            "url":"查询查复.html",
                            "includeVariables":true}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/实验室/b1_u24.png",
            "selected~":"images/实验室/b1_u24_selected.png",
            "mouseOver~":"images/实验室/b1_u24_selected.png",
            "disabled~":"images/实验室/b1_u24_disabled.png"}},
{
          "id":"9bdfeac0fcdf4a209119e54b728cf236",
          "label":"frm",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":159},
            "size":{
              "width":1184,
              "height":2920}},
          "adaptiveStyles":{
}},
{
          "id":"9dacae24c14843aaa5053be8fbbe77e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":178,
              "y":22},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9668e7d117421494f2cb3aace42cfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":178,
                  "y":22},
                "size":{
                  "width":200,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实验室",
                      "target":{
                        "targetType":"page",
                        "url":"实验室.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"71bf7546384e4dcd8846b01ccdafffef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":0,
              "y":15},
            "size":{
              "width":178,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"275c950e87a74803b8f22dace44bc35a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":0,
                  "y":15},
                "size":{
                  "width":178,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 OLDHome",
                      "target":{
                        "targetType":"page",
                        "url":"oldhome.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f9ddc5af95414f39b974d10a77da85ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":164,
              "y":9},
            "size":{
              "width":32,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"548d6cdf973c49e79ee2b6e129a929c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":164,
                  "y":9},
                "size":{
                  "width":32,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "1331e05edd57423aacb06fa062870c32":{
      "scriptId":"u0"},
    "848383545f2b4230b3f8e48a9e0fe0b1":{
      "scriptId":"u1"},
    "85ff4e385ecc42558fe6408c177f6fc1":{
      "scriptId":"u2"},
    "df3c8c598251456394ec4f7bef94a372":{
      "scriptId":"u3"},
    "d6c307e675c041698920a8b6bf063366":{
      "scriptId":"u4"},
    "9afea426e3d740cab1e8995bda2466c0":{
      "scriptId":"u5"},
    "7c63c67fb5f847e6a758f03bd52b95b3":{
      "scriptId":"u6"},
    "50772e8061e646b1bd54fe22b69b7a34":{
      "scriptId":"u7"},
    "eb973ba00be44e62b0564f3bca1ebe3f":{
      "scriptId":"u8"},
    "d3971e4da28041b787b7f9e705f7950e":{
      "scriptId":"u9"},
    "5bbf95933243438d8cfe4a2d88430d80":{
      "scriptId":"u10"},
    "ca2a83185c2b4e1b89b3cf7aa8a2e10e":{
      "scriptId":"u11"},
    "0481ac1bbc954308ad6e692000d9a396":{
      "scriptId":"u12"},
    "3c4e230194db4b88959abcb3b4d67bb6":{
      "scriptId":"u13"},
    "8916d871c0824deeab955df73380e321":{
      "scriptId":"u14"},
    "16ef9ea4e7eb4e3d8e2079cab31b46ad":{
      "scriptId":"u15"},
    "b481d7fad16a4cd4ac6de59777bf6bea":{
      "scriptId":"u16"},
    "78bef4b7150e490da20b926a290d9a4e":{
      "scriptId":"u17"},
    "a4ed4fae471d45c1895292f8ecd09855":{
      "scriptId":"u18"},
    "eff30aef420f42c49526e391e03b3ecc":{
      "scriptId":"u19"},
    "f52ffa4debd746bf8856c871a83d748c":{
      "scriptId":"u20"},
    "5f7d2259ed204c31bc4cb37f7b879d8f":{
      "scriptId":"u21"},
    "9d57511ef0c74cbcb759fb32d7172f99":{
      "scriptId":"u22"},
    "ef82551787814c1a8552c0caf50c316b":{
      "scriptId":"u23"},
    "021f3058b8684582988278a9eae27dc1":{
      "scriptId":"u24"},
    "5ff93e77da0f4c8398c227b6e5061530":{
      "scriptId":"u25"},
    "249aca9520dd4ae992408bc6fdbfb4ce":{
      "scriptId":"u26"},
    "92c3c0bccc0f4382840e802c755f9d5b":{
      "scriptId":"u27"},
    "a3d848a68d144f4b9603c27c2beeb6d7":{
      "scriptId":"u28"},
    "a6d0fa7981204f6d8f0ee2455dc89ee4":{
      "scriptId":"u29"},
    "135d476e00ac45ccbf83ecdf7f7fe006":{
      "scriptId":"u30"},
    "449e442c0efd4f978ec2eb02d6964cbd":{
      "scriptId":"u31"},
    "465f9bab4c924df986b9c99dffef276f":{
      "scriptId":"u32"},
    "6c7252b5801c4615b0f3a445c827547e":{
      "scriptId":"u33"},
    "8d5c840a2767487c94581f3946d6c08c":{
      "scriptId":"u34"},
    "d8e51be3ebd7448e8748661d1ff533ce":{
      "scriptId":"u35"},
    "9bdfeac0fcdf4a209119e54b728cf236":{
      "scriptId":"u36"},
    "9dacae24c14843aaa5053be8fbbe77e6":{
      "scriptId":"u37"},
    "7a9668e7d117421494f2cb3aace42cfb":{
      "scriptId":"u38"},
    "71bf7546384e4dcd8846b01ccdafffef":{
      "scriptId":"u39"},
    "275c950e87a74803b8f22dace44bc35a":{
      "scriptId":"u40"},
    "f9ddc5af95414f39b974d10a77da85ae":{
      "scriptId":"u41"},
    "548d6cdf973c49e79ee2b6e129a929c5":{
      "scriptId":"u42"}}});