$axure.loadCurrentPage({
  "url":"gsfstellar.html",
  "generationDate":new Date(1482495096622.39),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ad0ecfaaa15549fea5336b60ff53f756",
    "type":"Axure:Page",
    "name":"GSFstellar",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4e5e078ec23a42eb99b5acd0d94434da",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":360,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25cee4b13e4642c1a44b3ff6960307b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":360,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 GSFstellar",
                      "target":{
                        "targetType":"page",
                        "url":"gsfstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u57.png"}},
{
          "id":"1a373faa9bbd46b4bcdfc4a6a69482e7",
          "label":"",
          "type":"menuObject",
          "styleType":"menuObject",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":550,
              "y":0},
            "size":{
              "width":580,
              "height":32},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0708725fb7bf4afb8873446267336591",
              "label":"",
              "type":"table",
              "styleType":"table",
              "visible":true,
              "style":{
                "size":{
                  "width":580,
                  "height":32}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2df8740e19c7493d916352e449b6eff6",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "size":{
                      "width":180,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c1683fb1755049cbb0a1ac5e290a3bd3",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "size":{
                          "width":180,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 新窗口/标签页 打开 http://150.242.56.116",
                              "target":{
                                "targetType":"webUrl",
                                "urlLiteral":{
                                  "exprType":"stringLiteral",
                                  "value":"http://150.242.56.116",
                                  "stos":[]},
                                "includeVariables":false},
                              "linkType":"new"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"07d1d8b6a600479abe3e60aef814fccb",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":260,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"157306a7755a4a99a15ca8df04fe6b39",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":260,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bd53c43fff014f2f92ebcc46774cd622",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":340,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4685dc776cac4aafb16b19986533164b",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":340,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d9ed3e5c06ef4e0ea3898be8eb2e1144",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":420,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d26abed346e3491e8407e1bb59502162",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":420,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"eed6e68df9934c598656cc15cd960675",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"587746212eaa4f42b68af26db04dbf78",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":500,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7f119a6481654b92819198588636accc",
                  "label":"",
                  "type":"tableCell",
                  "styleType":"tableCell",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":180,
                      "y":0},
                    "size":{
                      "width":80,
                      "height":32},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"be562375d10e4e22b6b8b283742ecb90",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "location":{
                          "x":180,
                          "y":0},
                        "size":{
                          "width":80,
                          "height":32},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"e0e933fbe63241cdae097f33ed7637bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":26,
              "y":136},
            "size":{
              "width":634,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c7a5aa82cc9410e8dcfe039066ea88d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":26,
                  "y":136},
                "size":{
                  "width":634,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 实验室",
                      "target":{
                        "targetType":"page",
                        "url":"实验室.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5f5a7b4c3bf45faa182adcdc54a81b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":26,
              "y":167},
            "size":{
              "width":615,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70c2af11b9a8467e83b13ed5c52df654",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":26,
                  "y":167},
                "size":{
                  "width":615,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94c63f894b374c9392f2dd132ecbc971",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10.5,
              "y":1410},
            "size":{
              "width":1131,
              "height":541}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfc0e10af432451ca4cfdb0fc9dd5e6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10.5,
                  "y":1410},
                "size":{
                  "width":1131,
                  "height":541}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/lefinshare/u53.png"}},
{
          "id":"614e1f130df1479ea4d7c9371f3b26da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "horizontalAlignment":"right",
            "location":{
              "x":712,
              "y":2051},
            "size":{
              "width":383,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd0296f1b9eb496698dbd6182acfa041",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"right",
                "location":{
                  "x":712,
                  "y":2051},
                "size":{
                  "width":383,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d5e726dc2ff54f6aad44faa7afe89308",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":431,
              "y":1937},
            "size":{
              "width":262,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e5b0df8f9a4cc29d0c2a4572faf92f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":431,
                  "y":1937},
                "size":{
                  "width":262,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBDstellar",
                      "target":{
                        "targetType":"page",
                        "url":"cbdstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u59.png"}},
{
          "id":"b018c7aaf8124b338994fafcc4c3e121",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":77,
              "y":2014},
            "size":{
              "width":270,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bc8484b8758438ba6953d0b3826513c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":77,
                  "y":2014},
                "size":{
                  "width":270,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CBRstellar",
                      "target":{
                        "targetType":"page",
                        "url":"cbrstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u61.png"}},
{
          "id":"59ded1603b344937a12fe3622d7b8bcb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":1980},
            "size":{
              "width":315,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7be3cde39d894cceb613569298c8285d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":1980},
                "size":{
                  "width":315,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 CCFstallar",
                      "target":{
                        "targetType":"page",
                        "url":"ccfstallar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u63.png"}},
{
          "id":"14389a61377e4d11a2bd02ac12cec228",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":2057},
            "size":{
              "width":248,
              "height":28},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2ab19c9d50d4171b5a6eb76a13eb61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":2057},
                "size":{
                  "width":248,
                  "height":28},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 SmallBankForum",
                      "target":{
                        "targetType":"page",
                        "url":"smallbankforum.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u67.png"}},
{
          "id":"4c16dff87abc4e52ae754a24a4ae2865",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":452,
              "y":2057},
            "size":{
              "width":232,
              "height":31}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b032ee390d774649b07aefecfe82c3ad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":452,
                  "y":2057},
                "size":{
                  "width":232,
                  "height":31}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 LeFinShare",
                      "target":{
                        "targetType":"page",
                        "url":"lefinshare.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/gsfstellar/u32.png"}},
{
          "id":"3b4ae35957b3403cbb7ef755ace9a9d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":1971},
            "size":{
              "width":305,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51750663ba2442d784cb102a80ca3cc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":1971},
                "size":{
                  "width":305,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 ABSstellar",
                      "target":{
                        "targetType":"page",
                        "url":"absstellar.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/lefinshare/u65.png"}},
{
          "id":"c561fa38e7c548cf8ba71d3c2aec5182",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":1040,
              "y":161},
            "size":{
              "width":90,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f73518e360e4a2aaa8cd08165ffca17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":1040,
                  "y":161},
                "size":{
                  "width":90,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a95d2c3e899a457bae4dd2cbfc4a23ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":1890},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b32eb10648a14086bb8389d19cdff146",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":1890},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aeb84c7ce8bf4feca44103cf29ff4a80",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":12,
              "y":76}},
          "adaptiveStyles":{
},
          "masterId":"4717aadb7a9c492ea52bae53c0fe7f92"},
{
          "id":"72f3c84d5681481dbd59991c69c21e8b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":196}},
          "adaptiveStyles":{
},
          "masterId":"0ad5b74807be43b7a053e1730e651192"},
{
          "id":"3c7ab4c742f046a9b1e091ca348bd9e2",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":196}},
          "adaptiveStyles":{
},
          "masterId":"61fbdc6491d648b498cdae46617e334d"},
{
          "id":"69feb635d0064977ace685da85661753",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":-15,
              "y":360},
            "size":{
              "width":1110,
              "height":850}},
          "adaptiveStyles":{
}},
{
          "id":"6f11536c34e841b093388c2cf74513a8",
          "label":"",
          "type":"inlineFrame",
          "styleType":"inlineFrame",
          "visible":true,
          "style":{
            "location":{
              "x":-31,
              "y":1210},
            "size":{
              "width":1110,
              "height":200}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "4717aadb7a9c492ea52bae53c0fe7f92":{
      "packageId":"4717aadb7a9c492ea52bae53c0fe7f92",
      "type":"Axure:Master",
      "name":"基础应用",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"09e8fc79a5f14c7a99eb5892e1876c40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":366,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ef32ff36f7a6431984dab72d0b1576e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":366,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://123.59.176.75",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://123.59.176.75",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"c53c95e85a454f048228bf7bb8661d99",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":110,
                "y":0},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5fa94b9cb02a4a809badae9c5c8744de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":110,
                    "y":0},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"d160475039954513a8916264a62070ce",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":452,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"94a75bef1a5545d785df4e03174d03d7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":452,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"92f1433b0dce44b38b3ba68d6bf7fcca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":537,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"114dee27480144969dd47c62a6c93e6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":537,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 新窗口/标签页 打开 http://150.242.56.112:9000/common/projectList.html",
                        "target":{
                          "targetType":"webUrl",
                          "urlLiteral":{
                            "exprType":"stringLiteral",
                            "value":"http://150.242.56.112:9000/common/projectList.html",
                            "stos":[]},
                          "includeVariables":false},
                        "linkType":"new"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"8ca5acff3129403e8d36c77c48bc40a5",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":622,
                "y":0},
              "size":{
                "width":78,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4c6845ac8d8045259cca7868db810013",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":622,
                    "y":0},
                  "size":{
                    "width":78,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u5.png",
              "selected~":"images/lefinshare/u5_selected.png",
              "mouseOver~":"images/lefinshare/u5_mouseOver.png",
              "mouseDown~":"images/lefinshare/u5_mouseOver.png",
              "disabled~":"images/lefinshare/u5_mouseOver.png"}},
{
            "id":"aee4d0c2646644319c435099ef39eec6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":710,
                "y":0},
              "size":{
                "width":148,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c252398d5e2a428ba18295db3e6e5f8e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":710,
                    "y":0},
                  "size":{
                    "width":148,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u15.png",
              "selected~":"images/lefinshare/u15_selected.png",
              "mouseOver~":"images/lefinshare/u15_mouseOver.png",
              "mouseDown~":"images/lefinshare/u15_mouseOver.png",
              "disabled~":"images/lefinshare/u15_mouseOver.png"}},
{
            "id":"e8f421743a96491892851fd3ae2a40c3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "size":{
                "width":100,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"323b12dd97194b68ba857706d3216507",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "size":{
                    "width":100,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u7.png",
              "selected~":"images/lefinshare/u7_selected.png",
              "mouseOver~":"images/lefinshare/u7_mouseOver.png",
              "mouseDown~":"images/lefinshare/u7_mouseOver.png",
              "disabled~":"images/lefinshare/u7_mouseOver.png"}},
{
            "id":"51b350f40bd343f18728a45ec923e313",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":220,
                "y":0},
              "size":{
                "width":136,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2e1f4cef9f2e49188ff642467e9cca34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":220,
                    "y":0},
                  "size":{
                    "width":136,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u19.png",
              "selected~":"images/lefinshare/u19_selected.png",
              "mouseOver~":"images/lefinshare/u19_mouseOver.png",
              "mouseDown~":"images/lefinshare/u19_mouseOver.png",
              "disabled~":"images/lefinshare/u19_mouseOver.png"}},
{
            "id":"a398525097514925bf1e3364afa2f1a4",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":868,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2474207010164e20978b0c450cc48635",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":868,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}},
{
            "id":"afba7c40d3b945129b691a8802891f5c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'微软雅黑 Regular', '微软雅黑'",
              "fontSize":"18px",
              "stateStyles":{
                "mouseOver":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF000000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF0099FF}},
                "disabled":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}}},
              "location":{
                "x":988,
                "y":0},
              "size":{
                "width":110,
                "height":40},
              "cornerRadiusTopLeft":"34"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d5dbc3d6059f4b039664550bfd50a180",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'微软雅黑 Regular', '微软雅黑'",
                  "fontSize":"18px",
                  "stateStyles":{
                    "mouseOver":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF000000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFFFFFF,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFF0099FF}},
                    "disabled":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFF666666,
                        "opacity":1},
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFCCCCCC}}},
                  "location":{
                    "x":988,
                    "y":0},
                  "size":{
                    "width":110,
                    "height":40},
                  "cornerRadiusTopLeft":"34"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/lefinshare/u21.png",
              "selected~":"images/lefinshare/u21_selected.png",
              "mouseOver~":"images/lefinshare/u21_mouseOver.png",
              "mouseDown~":"images/lefinshare/u21_mouseOver.png",
              "disabled~":"images/lefinshare/u21_mouseOver.png"}}]}},
    "0ad5b74807be43b7a053e1730e651192":{
      "packageId":"0ad5b74807be43b7a053e1730e651192",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
            "label":"topcampaints",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":681,
                "height":160}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"wait",
                        "description":"等待3000毫秒",
                        "waitTime":3000},
{
                        "action":"setPanelState",
                        "description":"设置 topcampaints to 下一步 向左滑动 out 500ms 向左滑动 in 500ms wrap repeat every 3000 ms",
                        "panelsToStates":[{
                            "panelPath":["ab8b93c14d654a7fac3f2a18cf8c3cc2"],
                            "stateInfo":{
                              "setStateType":"next",
                              "stateNumber":1,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":true,
                              "showWhenSet":false,
                              "repeat":3000,
                              "options":{
                                "animateOut":{
                                  "easing":"slideLeft",
                                  "duration":500},
                                "animateIn":{
                                  "easing":"slideLeft",
                                  "duration":500},
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"71f05a5938e04a09ac34b52219217f38",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"ac30936e697b4ccba0c69fd012c60ba7",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"278b2c708e9f4223b8c22c96de6bdd0e",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u45.png"}}]},
{
                "id":"b25f687248484d08a44a52ea76e6efb2",
                "label":"状态2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b11604d5c8434d7d91c65d3980187c9f",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"62e4ab509f9842798658f3c6422c6d8a",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u47.png"}}]},
{
                "id":"f21b66a172e84cedac7791bdc2d3848e",
                "label":"状态3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"19bf8be82cbf42d3b172703b7a7a1fb3",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8312d21c7eca4d9a955db2547f158789",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u49.png"}}]},
{
                "id":"c266683103084d3f920197991f8a267a",
                "label":"状态4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"4f5b9963e8dc44ed8f110df6d9f8af32",
                    "label":"",
                    "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":680,
                        "height":160}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"8c2674e6d00d4aa59cb7389b08d224b0",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"ab8b93c14d654a7fac3f2a18cf8c3cc2",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":680,
                            "height":160}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u51.png"}}]}]}]}},
    "61fbdc6491d648b498cdae46617e334d":{
      "packageId":"61fbdc6491d648b498cdae46617e334d",
      "type":"Axure:Master",
      "name":"更多消息",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"aa9c65ad014547878c7231230a6484ea",
            "label":"topcampaints",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":419,
                "height":160}},
            "adaptiveStyles":{
},
            "interactionMap":{
              "onLoad":{
                "description":"OnLoad",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"wait",
                        "description":"等待5000毫秒",
                        "waitTime":5000},
{
                        "action":"setPanelState",
                        "description":"设置 topcampaints to 下一步 淡入淡出 out 500ms 淡入淡出 in 500ms wrap repeat every 5000 ms",
                        "panelsToStates":[{
                            "panelPath":["aa9c65ad014547878c7231230a6484ea"],
                            "stateInfo":{
                              "setStateType":"next",
                              "stateNumber":2,
                              "stateValue":{
                                "exprType":"stringLiteral",
                                "value":"1",
                                "stos":[]},
                              "loop":true,
                              "showWhenSet":false,
                              "repeat":5000,
                              "options":{
                                "animateOut":{
                                  "easing":"fade",
                                  "duration":500},
                                "animateIn":{
                                  "easing":"fade",
                                  "duration":500},
                                "compress":false}}}]}]}]}},
            "scrollbars":"none",
            "fitToContent":false,
            "propagate":false,
            "diagrams":[{
                "id":"3ae82fa30cda41cca54dc3f0d646d3de",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"b01681d73c98441199246a6e37b2357a",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":420,
                        "height":161}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4646f876e79a4c9d9e1c50709d289663",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":420,
                            "height":161}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://150.242.56.112:9003",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://150.242.56.112:9003",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/lefinshare/u75.png"}}]},
{
                "id":"069e5e85cdf64dae9479dd4cdfafdfb3",
                "label":"状态2",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"537f19aa81074d6cab8ae3ff144f7113",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "size":{
                        "width":420,
                        "height":164},
                      "rotation":"0",
                      "textRotation":"0",
                      "borderWidth":"0",
                      "cornerRadiusTopLeft":"0"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"370655ada466455f85647fcc33bd3a11",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "size":{
                            "width":420,
                            "height":164},
                          "rotation":"0",
                          "textRotation":"0",
                          "borderWidth":"0",
                          "cornerRadiusTopLeft":"0"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u77.png"}},
{
                    "id":"f9f60104680a4f709579a854d7be7d4c",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"buttonShape",
                    "styleType":"h1",
                    "visible":true,
                    "style":{
                      "fontSize":"20px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":55,
                        "y":68},
                      "size":{
                        "width":310,
                        "height":24}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"37327b097ed446caa541b0e228ce73d4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontSize":"20px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":55,
                            "y":68},
                          "size":{
                            "width":310,
                            "height":24}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]},
{
                "id":"993dfe2b8ad74e19a65dfbc860281737",
                "label":"状态3",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"0a87521ea4a54eaa965ed88bba3054a5",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-230,
                        "y":-17},
                      "size":{
                        "width":680,
                        "height":190}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"691328232e4745be87abf2e8f390c830",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-230,
                            "y":-17},
                          "size":{
                            "width":680,
                            "height":190}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u49.png"}}]},
{
                "id":"f7153b7ed1734082874e567967e67d20",
                "label":"状态4",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"924ca9899a1c4018a7339f8c418ecd0f",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-170,
                        "y":-3},
                      "size":{
                        "width":680,
                        "height":164}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6f2c264cb4e947fabb497d345d7ae522",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-170,
                            "y":-3},
                          "size":{
                            "width":680,
                            "height":164}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/lefinshare/u51.png"}}]},
{
                "id":"3b96a2edd77e4e918d2a4495f6c70dbd",
                "label":"状态5",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"fad3e47fa11b4b2f9ed93683dcd4c4fb",
                    "label":"",
                    "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":-40,
                        "y":0},
                      "size":{
                        "width":470,
                        "height":164},
                      "cornerRadiusTopLeft":"2"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0764d68807a44b0783290af1d38daac4",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"aa9c65ad014547878c7231230a6484ea",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":-40,
                            "y":0},
                          "size":{
                            "width":470,
                            "height":164},
                          "cornerRadiusTopLeft":"2"},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 新窗口/标签页 打开 http://www.meimuzc.com",
                                "target":{
                                  "targetType":"webUrl",
                                  "urlLiteral":{
                                    "exprType":"stringLiteral",
                                    "value":"http://www.meimuzc.com",
                                    "stos":[]},
                                  "includeVariables":false},
                                "linkType":"new"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/lefinshare/u85.png"}}]}]}]}}},
  "objectPaths":{
    "4e5e078ec23a42eb99b5acd0d94434da":{
      "scriptId":"u0"},
    "25cee4b13e4642c1a44b3ff6960307b4":{
      "scriptId":"u1"},
    "1a373faa9bbd46b4bcdfc4a6a69482e7":{
      "scriptId":"u2"},
    "0708725fb7bf4afb8873446267336591":{
      "scriptId":"u3"},
    "2df8740e19c7493d916352e449b6eff6":{
      "scriptId":"u4"},
    "c1683fb1755049cbb0a1ac5e290a3bd3":{
      "scriptId":"u5"},
    "7f119a6481654b92819198588636accc":{
      "scriptId":"u6"},
    "be562375d10e4e22b6b8b283742ecb90":{
      "scriptId":"u7"},
    "07d1d8b6a600479abe3e60aef814fccb":{
      "scriptId":"u8"},
    "157306a7755a4a99a15ca8df04fe6b39":{
      "scriptId":"u9"},
    "bd53c43fff014f2f92ebcc46774cd622":{
      "scriptId":"u10"},
    "4685dc776cac4aafb16b19986533164b":{
      "scriptId":"u11"},
    "d9ed3e5c06ef4e0ea3898be8eb2e1144":{
      "scriptId":"u12"},
    "d26abed346e3491e8407e1bb59502162":{
      "scriptId":"u13"},
    "eed6e68df9934c598656cc15cd960675":{
      "scriptId":"u14"},
    "587746212eaa4f42b68af26db04dbf78":{
      "scriptId":"u15"},
    "e0e933fbe63241cdae097f33ed7637bb":{
      "scriptId":"u16"},
    "3c7a5aa82cc9410e8dcfe039066ea88d":{
      "scriptId":"u17"},
    "d5f5a7b4c3bf45faa182adcdc54a81b2":{
      "scriptId":"u18"},
    "70c2af11b9a8467e83b13ed5c52df654":{
      "scriptId":"u19"},
    "94c63f894b374c9392f2dd132ecbc971":{
      "scriptId":"u20"},
    "bfc0e10af432451ca4cfdb0fc9dd5e6d":{
      "scriptId":"u21"},
    "614e1f130df1479ea4d7c9371f3b26da":{
      "scriptId":"u22"},
    "cd0296f1b9eb496698dbd6182acfa041":{
      "scriptId":"u23"},
    "d5e726dc2ff54f6aad44faa7afe89308":{
      "scriptId":"u24"},
    "a9e5b0df8f9a4cc29d0c2a4572faf92f":{
      "scriptId":"u25"},
    "b018c7aaf8124b338994fafcc4c3e121":{
      "scriptId":"u26"},
    "3bc8484b8758438ba6953d0b3826513c":{
      "scriptId":"u27"},
    "59ded1603b344937a12fe3622d7b8bcb":{
      "scriptId":"u28"},
    "7be3cde39d894cceb613569298c8285d":{
      "scriptId":"u29"},
    "14389a61377e4d11a2bd02ac12cec228":{
      "scriptId":"u30"},
    "f2ab19c9d50d4171b5a6eb76a13eb61b":{
      "scriptId":"u31"},
    "4c16dff87abc4e52ae754a24a4ae2865":{
      "scriptId":"u32"},
    "b032ee390d774649b07aefecfe82c3ad":{
      "scriptId":"u33"},
    "3b4ae35957b3403cbb7ef755ace9a9d7":{
      "scriptId":"u34"},
    "51750663ba2442d784cb102a80ca3cc7":{
      "scriptId":"u35"},
    "c561fa38e7c548cf8ba71d3c2aec5182":{
      "scriptId":"u36"},
    "6f73518e360e4a2aaa8cd08165ffca17":{
      "scriptId":"u37"},
    "a95d2c3e899a457bae4dd2cbfc4a23ac":{
      "scriptId":"u38"},
    "b32eb10648a14086bb8389d19cdff146":{
      "scriptId":"u39"},
    "aeb84c7ce8bf4feca44103cf29ff4a80":{
      "scriptId":"u40",
      "09e8fc79a5f14c7a99eb5892e1876c40":{
        "scriptId":"u41"},
      "ef32ff36f7a6431984dab72d0b1576e7":{
        "scriptId":"u42"},
      "c53c95e85a454f048228bf7bb8661d99":{
        "scriptId":"u43"},
      "5fa94b9cb02a4a809badae9c5c8744de":{
        "scriptId":"u44"},
      "d160475039954513a8916264a62070ce":{
        "scriptId":"u45"},
      "94a75bef1a5545d785df4e03174d03d7":{
        "scriptId":"u46"},
      "92f1433b0dce44b38b3ba68d6bf7fcca":{
        "scriptId":"u47"},
      "114dee27480144969dd47c62a6c93e6e":{
        "scriptId":"u48"},
      "8ca5acff3129403e8d36c77c48bc40a5":{
        "scriptId":"u49"},
      "4c6845ac8d8045259cca7868db810013":{
        "scriptId":"u50"},
      "aee4d0c2646644319c435099ef39eec6":{
        "scriptId":"u51"},
      "c252398d5e2a428ba18295db3e6e5f8e":{
        "scriptId":"u52"},
      "e8f421743a96491892851fd3ae2a40c3":{
        "scriptId":"u53"},
      "323b12dd97194b68ba857706d3216507":{
        "scriptId":"u54"},
      "51b350f40bd343f18728a45ec923e313":{
        "scriptId":"u55"},
      "2e1f4cef9f2e49188ff642467e9cca34":{
        "scriptId":"u56"},
      "a398525097514925bf1e3364afa2f1a4":{
        "scriptId":"u57"},
      "2474207010164e20978b0c450cc48635":{
        "scriptId":"u58"},
      "afba7c40d3b945129b691a8802891f5c":{
        "scriptId":"u59"},
      "d5dbc3d6059f4b039664550bfd50a180":{
        "scriptId":"u60"}},
    "72f3c84d5681481dbd59991c69c21e8b":{
      "scriptId":"u61",
      "ab8b93c14d654a7fac3f2a18cf8c3cc2":{
        "scriptId":"u62"},
      "ac30936e697b4ccba0c69fd012c60ba7":{
        "scriptId":"u63"},
      "278b2c708e9f4223b8c22c96de6bdd0e":{
        "scriptId":"u64"},
      "b11604d5c8434d7d91c65d3980187c9f":{
        "scriptId":"u65"},
      "62e4ab509f9842798658f3c6422c6d8a":{
        "scriptId":"u66"},
      "19bf8be82cbf42d3b172703b7a7a1fb3":{
        "scriptId":"u67"},
      "8312d21c7eca4d9a955db2547f158789":{
        "scriptId":"u68"},
      "4f5b9963e8dc44ed8f110df6d9f8af32":{
        "scriptId":"u69"},
      "8c2674e6d00d4aa59cb7389b08d224b0":{
        "scriptId":"u70"}},
    "3c7ab4c742f046a9b1e091ca348bd9e2":{
      "scriptId":"u71",
      "aa9c65ad014547878c7231230a6484ea":{
        "scriptId":"u72"},
      "b01681d73c98441199246a6e37b2357a":{
        "scriptId":"u73"},
      "4646f876e79a4c9d9e1c50709d289663":{
        "scriptId":"u74"},
      "537f19aa81074d6cab8ae3ff144f7113":{
        "scriptId":"u75"},
      "370655ada466455f85647fcc33bd3a11":{
        "scriptId":"u76"},
      "f9f60104680a4f709579a854d7be7d4c":{
        "scriptId":"u77"},
      "37327b097ed446caa541b0e228ce73d4":{
        "scriptId":"u78"},
      "0a87521ea4a54eaa965ed88bba3054a5":{
        "scriptId":"u79"},
      "691328232e4745be87abf2e8f390c830":{
        "scriptId":"u80"},
      "924ca9899a1c4018a7339f8c418ecd0f":{
        "scriptId":"u81"},
      "6f2c264cb4e947fabb497d345d7ae522":{
        "scriptId":"u82"},
      "fad3e47fa11b4b2f9ed93683dcd4c4fb":{
        "scriptId":"u83"},
      "0764d68807a44b0783290af1d38daac4":{
        "scriptId":"u84"}},
    "69feb635d0064977ace685da85661753":{
      "scriptId":"u85"},
    "6f11536c34e841b093388c2cf74513a8":{
      "scriptId":"u86"}}});